<div class="m-l-10 m-t-10">
    <div class="btn-group dropup">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <img class="emoji emoji1f600" data-c="" data-r="1">
    </button>
    <div class="dropdown-menu dropdown-menu-left ">
        <div class="dropdown-item row col-12 fbmoti">
            <img class="emoji emoji1f600" data-c="😀">
            <img class="emoji emoji1f601" data-c="😁">
            <img class="emoji emoji1f602" data-c="😂">
            <img class="emoji emoji1f923" data-c="🤣">
            <img class="emoji emoji1f603" data-c="😃">
            <img class="emoji emoji1f604" data-c="😄">
            <img class="emoji emoji1f605" data-c="😅">
            <img class="emoji emoji1f606" data-c="😆">
            <img class="emoji emoji1f609" data-c="😉">
            <img class="emoji emoji1f60a" data-c="😊">
            <img class="emoji emoji1f60b" data-c="😋">
            <img class="emoji emoji1f60e" data-c="😎">
            <img class="emoji emoji1f60d" data-c="😍">
            <img class="emoji emoji1f618" data-c="😘">
            <img class="emoji emoji1f617" data-c="😗">
            <img class="emoji emoji1f619" data-c="😙">
            <img class="emoji emoji1f61a" data-c="😚">
            <img class="emoji emoji263a" data-c="☺">
            <img class="emoji emoji1f642" data-c="🙂">
            <img class="emoji emoji1f917" data-c="🤗">
            <img class="emoji emoji1f929" data-c="🤩">
            <img class="emoji emoji1f914" data-c="🤔">
            <img class="emoji emoji1f928" data-c="🤨">
            <img class="emoji emoji1f610" data-c="😐">
            <img class="emoji emoji1f611" data-c="😑">
            <img class="emoji emoji1f636" data-c="😶">
            <img class="emoji emoji1f644" data-c="🙄">
            <img class="emoji emoji1f60f" data-c="😏">
            <img class="emoji emoji1f623" data-c="😣">
            <img class="emoji emoji1f625" data-c="😥">
            <img class="emoji emoji1f62e" data-c="😮">
            <img class="emoji emoji1f910" data-c="🤐">
            <img class="emoji emoji1f62f" data-c="😯">
            <img class="emoji emoji1f62a" data-c="😪">
            <img class="emoji emoji1f62b" data-c="😫">
            <img class="emoji emoji1f634" data-c="😴">
            <img class="emoji emoji1f60c" data-c="😌">
            <img class="emoji emoji1f61b" data-c="😛">
            <img class="emoji emoji1f61c" data-c="😜">
            <img class="emoji emoji1f61d" data-c="😝">
            <img class="emoji emoji1f924" data-c="🤤">
            <img class="emoji emoji1f612" data-c="😒">
            <img class="emoji emoji1f613" data-c="😓">
            <img class="emoji emoji1f614" data-c="😔">
            <img class="emoji emoji1f615" data-c="😕">
            <img class="emoji emoji1f643" data-c="🙃">
            <img class="emoji emoji1f911" data-c="🤑">
            <img class="emoji emoji1f632" data-c="😲">
            <img class="emoji emoji2639" data-c="☹">
            <img class="emoji emoji1f641" data-c="🙁">
            <img class="emoji emoji1f616" data-c="😖">
            <img class="emoji emoji1f61e" data-c="😞">
            <img class="emoji emoji1f61f" data-c="😟">
            <img class="emoji emoji1f624" data-c="😤">
            <img class="emoji emoji1f622" data-c="😢">
            <img class="emoji emoji1f62d" data-c="😭">
            <img class="emoji emoji1f626" data-c="😦">
            <img class="emoji emoji1f627" data-c="😧">
            <img class="emoji emoji1f628" data-c="😨">
            <img class="emoji emoji1f629" data-c="😩">
            <img class="emoji emoji1f92f" data-c="🤯">
            <img class="emoji emoji1f62c" data-c="😬">
            <img class="emoji emoji1f630" data-c="😰">
            <img class="emoji emoji1f631" data-c="😱">
            <img class="emoji emoji1f633" data-c="😳">
            <img class="emoji emoji1f92a" data-c="🤪">
            <img class="emoji emoji1f635" data-c="😵">
            <img class="emoji emoji1f621" data-c="😡">
            <img class="emoji emoji1f620" data-c="😠">
            <img class="emoji emoji1f92c" data-c="🤬">
            <img class="emoji emoji1f637" data-c="😷">
            <img class="emoji emoji1f912" data-c="🤒">
            <img class="emoji emoji1f915" data-c="🤕">
            <img class="emoji emoji1f922" data-c="🤢">
            <img class="emoji emoji1f92e" data-c="🤮">
            <img class="emoji emoji1f927" data-c="🤧">
            <img class="emoji emoji1f607" data-c="😇">
            <img class="emoji emoji1f920" data-c="🤠">
            <img class="emoji emoji1f921" data-c="🤡">
            <img class="emoji emoji1f925" data-c="🤥">
            <img class="emoji emoji1f92b" data-c="🤫">
            <img class="emoji emoji1f92d" data-c="🤭">
            <img class="emoji emoji1f9d0" data-c="🧐">
            <img class="emoji emoji1f913" data-c="🤓">
            <img class="emoji emoji1f608" data-c="😈">
            <img class="emoji emoji1f47f" data-c="👿">
            <img class="emoji emoji1f479" data-c="👹">
            <img class="emoji emoji1f47a" data-c="👺">
            <img class="emoji emoji1f480" data-c="💀">
            <img class="emoji emoji2620" data-c="☠">
            <img class="emoji emoji1f47b" data-c="👻">
            <img class="emoji emoji1f47d" data-c="👽">
            <img class="emoji emoji1f47e" data-c="👾">
            <img class="emoji emoji1f916" data-c="🤖">
            <img class="emoji emoji1f4a9" data-c="💩">
            <img class="emoji emoji1f63a" data-c="😺">
            <img class="emoji emoji1f638" data-c="😸">
            <img class="emoji emoji1f639" data-c="😹">
            <img class="emoji emoji1f63b" data-c="😻">
            <img class="emoji emoji1f63c" data-c="😼">
            <img class="emoji emoji1f63d" data-c="😽">
            <img class="emoji emoji1f640" data-c="🙀">
            <img class="emoji emoji1f63f" data-c="😿">
            <img class="emoji emoji1f63e" data-c="😾">
            <img class="emoji emoji1f648" data-c="🙈">
            <img class="emoji emoji1f649" data-c="🙉">
            <img class="emoji emoji1f64a" data-c="🙊">
            <img class="emoji emoji1f476" data-c="👶">
            <img class="emoji emoji1f9d2" data-c="🧒">
            <img class="emoji emoji1f466" data-c="👦">
            <img class="emoji emoji1f467" data-c="👧">
            <img class="emoji emoji1f9d1" data-c="🧑">
            <img class="emoji emoji1f468" data-c="👨">
            <img class="emoji emoji1f469" data-c="👩">
            <img class="emoji emoji1f9d3" data-c="🧓">
            <img class="emoji emoji1f474" data-c="👴">
            <img class="emoji emoji1f475" data-c="👵">
            <img class="emoji emoji1f933" data-c="🤳">
            <img class="emoji emoji1f4aa" data-c="💪">
            <img class="emoji emoji1f448" data-c="👈">
            <img class="emoji emoji1f449" data-c="👉">
            <img class="emoji emoji261d" data-c="☝">
            <img class="emoji emoji1f446" data-c="👆">
            <img class="emoji emoji1f595" data-c="🖕">
            <img class="emoji emoji1f447" data-c="👇">
            <img class="emoji emoji270c" data-c="✌">
            <img class="emoji emoji1f91e" data-c="🤞">
            <img class="emoji emoji1f596" data-c="🖖">
            <img class="emoji emoji1f918" data-c="🤘">
            <img class="emoji emoji1f919" data-c="🤙">
            <img class="emoji emoji1f590" data-c="🖐">
            <img class="emoji emoji270b" data-c="✋">
            <img class="emoji emoji1f44c" data-c="👌">
            <img class="emoji emoji1f44d" data-c="👍">
            <img class="emoji emoji1f44e" data-c="👎">
            <img class="emoji emoji270a" data-c="✊">
            <img class="emoji emoji1f44a" data-c="👊">
            <img class="emoji emoji1f91b" data-c="🤛">
            <img class="emoji emoji1f91c" data-c="🤜">
            <img class="emoji emoji1f91a" data-c="🤚">
            <img class="emoji emoji1f44b" data-c="👋">
            <img class="emoji emoji1f91f" data-c="🤟">
            <img class="emoji emoji270d" data-c="✍">
            <img class="emoji emoji1f44f" data-c="👏">
            <img class="emoji emoji1f450" data-c="👐">
            <img class="emoji emoji1f64c" data-c="🙌">
            <img class="emoji emoji1f932" data-c="🤲">
            <img class="emoji emoji1f64f" data-c="🙏">
            <img class="emoji emoji1f91d" data-c="🤝">
            <img class="emoji emoji1f485" data-c="💅">
            <img class="emoji emoji1f442" data-c="👂">
            <img class="emoji emoji1f443" data-c="👃">
            <img class="emoji emoji1f463" data-c="👣">
            <img class="emoji emoji1f440" data-c="👀">
            <img class="emoji emoji1f441" data-c="👁">
            <img class="emoji emoji1f441-200d-1f5e8" data-c="👁&zwj;🗨">
            <img class="emoji emoji1f9e0" data-c="🧠">
            <img class="emoji emoji1f445" data-c="👅">
            <img class="emoji emoji1f444" data-c="👄">
            <img class="emoji emoji1f48b" data-c="💋">
            <img class="emoji emoji1f498" data-c="💘">
            <img class="emoji emoji2764" data-c="❤">
            <img class="emoji emoji1f493" data-c="💓">
            <img class="emoji emoji1f494" data-c="💔">
            <img class="emoji emoji1f495" data-c="💕">
            <img class="emoji emoji1f496" data-c="💖">
            <img class="emoji emoji1f497" data-c="💗">
            <img class="emoji emoji1f499" data-c="💙">
            <img class="emoji emoji1f49a" data-c="💚">
            <img class="emoji emoji1f49b" data-c="💛">
            <img class="emoji emoji1f9e1" data-c="🧡">
            <img class="emoji emoji1f49c" data-c="💜">
            <img class="emoji emoji1f5a4" data-c="🖤">
            <img class="emoji emoji1f49d" data-c="💝">
            <img class="emoji emoji1f49e" data-c="💞">
            <img class="emoji emoji1f49f" data-c="💟">
            <img class="emoji emoji2763" data-c="❣">
            <img class="emoji emoji1f48c" data-c="💌">
            <img class="emoji emoji1f4a4" data-c="💤">
            <img class="emoji emoji1f4a2" data-c="💢">
            <img class="emoji emoji1f4a3" data-c="💣">
            <img class="emoji emoji1f4a5" data-c="💥">
            <img class="emoji emoji1f4a6" data-c="💦">
            <img class="emoji emoji1f4a8" data-c="💨">
            <img class="emoji emoji1f4ab" data-c="💫">
            <img class="emoji emoji1f4ac" data-c="💬">
            <img class="emoji emoji1f5e8" data-c="🗨">
            <img class="emoji emoji1f5ef" data-c="🗯">
            <img class="emoji emoji1f4ad" data-c="💭">
            <img class="emoji emoji1f573" data-c="🕳">
            <img class="emoji emoji1f934" data-c="🤴">
            <img class="emoji emoji1f478" data-c="👸">
            <img class="emoji emoji1f473-200d-2642" data-c="👳‍♂">
            <img class="emoji emoji1f473-200d-2640" data-c="👳‍♀">
            <img class="emoji emoji1f472" data-c="👲">
            <img class="emoji emoji1f9d5" data-c="🧕">
            <img class="emoji emoji1f9d4" data-c="🧔">
            <img class="emoji emoji1f471-200d-2642" data-c="👱‍♂">
            <img class="emoji emoji1f471-200d-2640" data-c="👱‍♀">
            <img class="emoji emoji1f935" data-c="🤵">
            <img class="emoji emoji1f470" data-c="👰">
            <img class="emoji emoji1f930" data-c="🤰">
            <img class="emoji emoji1f931" data-c="🤱">
            <img class="emoji emoji1f47c" data-c="👼">
            <img class="emoji emoji1f385" data-c="🎅">
            <img class="emoji emoji1f936" data-c="🤶">
            <img class="emoji emoji1f9d9-200d-2640" data-c="🧙‍♀">
            <img class="emoji emoji1f9d9-200d-2642" data-c="🧙‍♂">
            <img class="emoji emoji1f9da-200d-2640" data-c="🧚‍♀">
            <img class="emoji emoji1f9da-200d-2642" data-c="🧚‍♂">
            <img class="emoji emoji1f9db-200d-2640" data-c="🧛‍♀">
            <img class="emoji emoji1f9db-200d-2642" data-c="🧛‍♂">
            <img class="emoji emoji1f9dc-200d-2640" data-c="🧜‍♀">
            <img class="emoji emoji1f9dc-200d-2642" data-c="🧜‍♂">
            <img class="emoji emoji1f9dd-200d-2640" data-c="🧝‍♀">
            <img class="emoji emoji1f9dd-200d-2642" data-c="🧝‍♂">
            <img class="emoji emoji1f9de-200d-2640" data-c="🧞‍♀">
            <img class="emoji emoji1f9de-200d-2642" data-c="🧞‍♂">
            <img class="emoji emoji1f9df-200d-2640" data-c="🧟‍♀">
            <img class="emoji emoji1f9df-200d-2642" data-c="🧟‍♂">
            <img class="emoji emoji1f64d-200d-2642" data-c="🙍‍♂">
            <img class="emoji emoji1f64d-200d-2640" data-c="🙍‍♀">
            <img class="emoji emoji1f64e-200d-2642" data-c="🙎‍♂">
            <img class="emoji emoji1f64e-200d-2640" data-c="🙎‍♀">
            <img class="emoji emoji1f645-200d-2642" data-c="🙅‍♂">
            <img class="emoji emoji1f645-200d-2640" data-c="🙅‍♀">
            <img class="emoji emoji1f646-200d-2642" data-c="🙆‍♂">
            <img class="emoji emoji1f646-200d-2640" data-c="🙆‍♀">
            <img class="emoji emoji1f481-200d-2642" data-c="💁‍♂">
            <img class="emoji emoji1f481-200d-2640" data-c="💁‍♀">
            <img class="emoji emoji1f64b-200d-2642" data-c="🙋‍♂">
            <img class="emoji emoji1f64b-200d-2640" data-c="🙋‍♀">
            <img class="emoji emoji1f647-200d-2642" data-c="🙇‍♂">
            <img class="emoji emoji1f647-200d-2640" data-c="🙇‍♀">
            <img class="emoji emoji1f926-200d-2642" data-c="🤦‍♂">
            <img class="emoji emoji1f926-200d-2640" data-c="🤦‍♀">
            <img class="emoji emoji1f937-200d-2642" data-c="🤷‍♂">
            <img class="emoji emoji1f937-200d-2640" data-c="🤷‍♀">
            <img class="emoji emoji1f486-200d-2642" data-c="💆‍♂">
            <img class="emoji emoji1f486-200d-2640" data-c="💆‍♀">
            <img class="emoji emoji1f487-200d-2642" data-c="💇‍♂">
            <img class="emoji emoji1f487-200d-2640" data-c="💇‍♀">
            <img class="emoji emoji1f6b6-200d-2642" data-c="🚶‍♂">
            <img class="emoji emoji1f6b6-200d-2640" data-c="🚶‍♀">
            <img class="emoji emoji1f3c3-200d-2642" data-c="🏃‍♂">
            <img class="emoji emoji1f3c3-200d-2640" data-c="🏃‍♀">
            <img class="emoji emoji1f483" data-c="💃">
            <img class="emoji emoji1f57a" data-c="🕺">
            <img class="emoji emoji1f46f-200d-2642" data-c="👯‍♂">
            <img class="emoji emoji1f46f-200d-2640" data-c="👯‍♀">
            <img class="emoji emoji1f9d6-200d-2640" data-c="🧖‍♀">
            <img class="emoji emoji1f9d6-200d-2642" data-c="🧖‍♂">
            <img class="emoji emoji1f6c0" data-c="🛀">
            <img class="emoji emoji1f6cc" data-c="🛌">
            <img class="emoji emoji1f574" data-c="🕴">
            <img class="emoji emoji1f5e3" data-c="🗣">
            <img class="emoji emoji1f464" data-c="👤">
            <img class="emoji emoji1f465" data-c="👥">
            <img class="emoji emoji1f46b" data-c="👫">
            <img class="emoji emoji1f46c" data-c="👬">
            <img class="emoji emoji1f46d" data-c="👭">
            <img class="emoji emoji1f469-200d-2764-200d-1f48b-200d-1f468" data-c="👩&zwj;❤&zwj;💋&zwj;👨">
            <img class="emoji emoji1f468-200d-2764-200d-1f48b-200d-1f468" data-c="👨&zwj;❤&zwj;💋&zwj;👨">
            <img class="emoji emoji1f469-200d-2764-200d-1f48b-200d-1f469" data-c="👩&zwj;❤&zwj;💋&zwj;👩">
            <img class="emoji emoji1f469-200d-2764-200d-1f468" data-c="👩&zwj;❤&zwj;👨">
            <img class="emoji emoji1f468-200d-2764-200d-1f468" data-c="👨&zwj;❤&zwj;👨">
            <img class="emoji emoji1f469-200d-2764-200d-1f469" data-c="👩&zwj;❤&zwj;👩">
        </div>
    </div>
</div>
</div>
<div class="m-l-10 m-t-10">
    <div class="btn-group dropup">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <img class="emoji emoji1f40e" data-c="" data-r="1">
    </button>
    <div class="dropdown-menu dropdown-menu-left">
        <div class="dropdown-item row col-12 fbmoti">
            <img class="emoji emoji1f435" data-c="🐵">
            <img class="emoji emoji1f412" data-c="🐒">
            <img class="emoji emoji1f98d" data-c="🦍">
            <img class="emoji emoji1f436" data-c="🐶">
            <img class="emoji emoji1f415" data-c="🐕">
            <img class="emoji emoji1f429" data-c="🐩">
            <img class="emoji emoji1f43a" data-c="🐺">
            <img class="emoji emoji1f98a" data-c="🦊">
            <img class="emoji emoji1f431" data-c="🐱">
            <img class="emoji emoji1f408" data-c="🐈">
            <img class="emoji emoji1f981" data-c="🦁">
            <img class="emoji emoji1f42f" data-c="🐯">
            <img class="emoji emoji1f405" data-c="🐅">
            <img class="emoji emoji1f406" data-c="🐆">
            <img class="emoji emoji1f434" data-c="🐴">
            <img class="emoji emoji1f40e" data-c="🐎">
            <img class="emoji emoji1f984" data-c="🦄">
            <img class="emoji emoji1f993" data-c="🦓">
            <img class="emoji emoji1f98c" data-c="🦌">
            <img class="emoji emoji1f42e" data-c="🐮">
            <img class="emoji emoji1f402" data-c="🐂">
            <img class="emoji emoji1f403" data-c="🐃">
            <img class="emoji emoji1f404" data-c="🐄">
            <img class="emoji emoji1f437" data-c="🐷">
            <img class="emoji emoji1f416" data-c="🐖">
            <img class="emoji emoji1f417" data-c="🐗">
            <img class="emoji emoji1f43d" data-c="🐽">
            <img class="emoji emoji1f40f" data-c="🐏">
            <img class="emoji emoji1f411" data-c="🐑">
            <img class="emoji emoji1f410" data-c="🐐">
            <img class="emoji emoji1f42a" data-c="🐪">
            <img class="emoji emoji1f42b" data-c="🐫">
            <img class="emoji emoji1f992" data-c="🦒">
            <img class="emoji emoji1f418" data-c="🐘">
            <img class="emoji emoji1f98f" data-c="🦏">
            <img class="emoji emoji1f42d" data-c="🐭">
            <img class="emoji emoji1f401" data-c="🐁">
            <img class="emoji emoji1f400" data-c="🐀">
            <img class="emoji emoji1f439" data-c="🐹">
            <img class="emoji emoji1f430" data-c="🐰">
            <img class="emoji emoji1f407" data-c="🐇">
            <img class="emoji emoji1f43f" data-c="🐿">
            <img class="emoji emoji1f994" data-c="🦔">
            <img class="emoji emoji1f987" data-c="🦇">
            <img class="emoji emoji1f43b" data-c="🐻">
            <img class="emoji emoji1f428" data-c="🐨">
            <img class="emoji emoji1f43c" data-c="🐼">
            <img class="emoji emoji1f43e" data-c="🐾">
            <img class="emoji emoji1f983" data-c="🦃">
            <img class="emoji emoji1f414" data-c="🐔">
            <img class="emoji emoji1f413" data-c="🐓">
            <img class="emoji emoji1f423" data-c="🐣">
            <img class="emoji emoji1f424" data-c="🐤">
            <img class="emoji emoji1f425" data-c="🐥">
            <img class="emoji emoji1f426" data-c="🐦">
            <img class="emoji emoji1f427" data-c="🐧">
            <img class="emoji emoji1f54a" data-c="🕊">
            <img class="emoji emoji1f985" data-c="🦅">
            <img class="emoji emoji1f986" data-c="🦆">
            <img class="emoji emoji1f989" data-c="🦉">
            <img class="emoji emoji1f438" data-c="🐸">
            <img class="emoji emoji1f40a" data-c="🐊">
            <img class="emoji emoji1f422" data-c="🐢">
            <img class="emoji emoji1f98e" data-c="🦎">
            <img class="emoji emoji1f40d" data-c="🐍">
            <img class="emoji emoji1f432" data-c="🐲">
            <img class="emoji emoji1f409" data-c="🐉">
            <img class="emoji emoji1f995" data-c="🦕">
            <img class="emoji emoji1f996" data-c="🦖">
            <img class="emoji emoji1f433" data-c="🐳">
            <img class="emoji emoji1f40b" data-c="🐋">
            <img class="emoji emoji1f42c" data-c="🐬">
            <img class="emoji emoji1f41f" data-c="🐟">
            <img class="emoji emoji1f420" data-c="🐠">
            <img class="emoji emoji1f421" data-c="🐡">
            <img class="emoji emoji1f988" data-c="🦈">
            <img class="emoji emoji1f419" data-c="🐙">
            <img class="emoji emoji1f41a" data-c="🐚">
            <img class="emoji emoji1f980" data-c="🦀">
            <img class="emoji emoji1f990" data-c="🦐">
            <img class="emoji emoji1f991" data-c="🦑">
            <img class="emoji emoji1f40c" data-c="🐌">
            <img class="emoji emoji1f98b" data-c="🦋">
            <img class="emoji emoji1f41b" data-c="🐛">
            <img class="emoji emoji1f41c" data-c="🐜">
            <img class="emoji emoji1f41d" data-c="🐝">
            <img class="emoji emoji1f41e" data-c="🐞">
            <img class="emoji emoji1f997" data-c="🦗">
            <img class="emoji emoji1f577" data-c="🕷">
            <img class="emoji emoji1f578" data-c="🕸">
            <img class="emoji emoji1f982" data-c="🦂">
            <img class="emoji emoji1f490" data-c="💐">
            <img class="emoji emoji1f338" data-c="🌸">
            <img class="emoji emoji1f4ae" data-c="💮">
            <img class="emoji emoji1f3f5" data-c="🏵">
            <img class="emoji emoji1f339" data-c="🌹">
            <img class="emoji emoji1f940" data-c="🥀">
            <img class="emoji emoji1f33a" data-c="🌺">
            <img class="emoji emoji1f33b" data-c="🌻">
            <img class="emoji emoji1f33c" data-c="🌼">
            <img class="emoji emoji1f337" data-c="🌷">
            <img class="emoji emoji1f331" data-c="🌱">
            <img class="emoji emoji1f332" data-c="🌲">
            <img class="emoji emoji1f333" data-c="🌳">
            <img class="emoji emoji1f334" data-c="🌴">
            <img class="emoji emoji1f335" data-c="🌵">
            <img class="emoji emoji1f33e" data-c="🌾">
            <img class="emoji emoji1f33f" data-c="🌿">
            <img class="emoji emoji2618" data-c="☘">
            <img class="emoji emoji1f340" data-c="🍀">
            <img class="emoji emoji1f341" data-c="🍁">
            <img class="emoji emoji1f342" data-c="🍂">
            <img class="emoji emoji1f343" data-c="🍃">
        </div>
    </div>
</div>
</div>
<div class="m-l-10 m-t-10">
    <div class="btn-group dropup">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <img class="emoji emoji1f955" data-c="" data-r="1">
    </button>
    <div class="dropdown-menu dropdown-menu-left">
        <div class="dropdown-item row col-12 fbmoti">
            <img class="emoji emoji1f347" data-c="🍇">
            <img class="emoji emoji1f348" data-c="🍈">
            <img class="emoji emoji1f349" data-c="🍉">
            <img class="emoji emoji1f34a" data-c="🍊">
            <img class="emoji emoji1f34b" data-c="🍋">
            <img class="emoji emoji1f34c" data-c="🍌">
            <img class="emoji emoji1f34d" data-c="🍍">
            <img class="emoji emoji1f34e" data-c="🍎">
            <img class="emoji emoji1f34f" data-c="🍏">
            <img class="emoji emoji1f350" data-c="🍐">
            <img class="emoji emoji1f351" data-c="🍑">
            <img class="emoji emoji1f352" data-c="🍒">
            <img class="emoji emoji1f353" data-c="🍓">
            <img class="emoji emoji1f95d" data-c="🥝">
            <img class="emoji emoji1f345" data-c="🍅">
            <img class="emoji emoji1f965" data-c="🥥">
            <img class="emoji emoji1f951" data-c="🥑">
            <img class="emoji emoji1f346" data-c="🍆">
            <img class="emoji emoji1f954" data-c="🥔">
            <img class="emoji emoji1f955" data-c="🥕">
            <img class="emoji emoji1f33d" data-c="🌽">
            <img class="emoji emoji1f336" data-c="🌶">
            <img class="emoji emoji1f952" data-c="🥒">
            <img class="emoji emoji1f966" data-c="🥦">
            <img class="emoji emoji1f344" data-c="🍄">
            <img class="emoji emoji1f95c" data-c="🥜">
            <img class="emoji emoji1f330" data-c="🌰">
            <img class="emoji emoji1f35e" data-c="🍞">
            <img class="emoji emoji1f950" data-c="🥐">
            <img class="emoji emoji1f956" data-c="🥖">
            <img class="emoji emoji1f968" data-c="🥨">
            <img class="emoji emoji1f95e" data-c="🥞">
            <img class="emoji emoji1f9c0" data-c="🧀">
            <img class="emoji emoji1f356" data-c="🍖">
            <img class="emoji emoji1f357" data-c="🍗">
            <img class="emoji emoji1f969" data-c="🥩">
            <img class="emoji emoji1f953" data-c="🥓">
            <img class="emoji emoji1f354" data-c="🍔">
            <img class="emoji emoji1f35f" data-c="🍟">
            <img class="emoji emoji1f355" data-c="🍕">
            <img class="emoji emoji1f32d" data-c="🌭">
            <img class="emoji emoji1f96a" data-c="🥪">
            <img class="emoji emoji1f32e" data-c="🌮">
            <img class="emoji emoji1f32f" data-c="🌯">
            <img class="emoji emoji1f959" data-c="🥙">
            <img class="emoji emoji1f95a" data-c="🥚">
            <img class="emoji emoji1f373" data-c="🍳">
            <img class="emoji emoji1f958" data-c="🥘">
            <img class="emoji emoji1f372" data-c="🍲">
            <img class="emoji emoji1f963" data-c="🥣">
            <img class="emoji emoji1f957" data-c="🥗">
            <img class="emoji emoji1f37f" data-c="🍿">
            <img class="emoji emoji1f96b" data-c="🥫">
            <img class="emoji emoji1f371" data-c="🍱">
            <img class="emoji emoji1f358" data-c="🍘">
            <img class="emoji emoji1f359" data-c="🍙">
            <img class="emoji emoji1f35a" data-c="🍚">
            <img class="emoji emoji1f35b" data-c="🍛">
            <img class="emoji emoji1f35c" data-c="🍜">
            <img class="emoji emoji1f35d" data-c="🍝">
            <img class="emoji emoji1f360" data-c="🍠">
            <img class="emoji emoji1f362" data-c="🍢">
            <img class="emoji emoji1f363" data-c="🍣">
            <img class="emoji emoji1f364" data-c="🍤">
            <img class="emoji emoji1f365" data-c="🍥">
            <img class="emoji emoji1f361" data-c="🍡">
            <img class="emoji emoji1f95f" data-c="🥟">
            <img class="emoji emoji1f960" data-c="🥠">
            <img class="emoji emoji1f961" data-c="🥡">
            <img class="emoji emoji1f366" data-c="🍦">
            <img class="emoji emoji1f367" data-c="🍧">
            <img class="emoji emoji1f368" data-c="🍨">
            <img class="emoji emoji1f369" data-c="🍩">
            <img class="emoji emoji1f36a" data-c="🍪">
            <img class="emoji emoji1f382" data-c="🎂">
            <img class="emoji emoji1f370" data-c="🍰">
            <img class="emoji emoji1f967" data-c="🥧">
            <img class="emoji emoji1f36b" data-c="🍫">
            <img class="emoji emoji1f36c" data-c="🍬">
            <img class="emoji emoji1f36d" data-c="🍭">
            <img class="emoji emoji1f36e" data-c="🍮">
            <img class="emoji emoji1f36f" data-c="🍯">
            <img class="emoji emoji1f37c" data-c="🍼">
            <img class="emoji emoji1f95b" data-c="🥛">
            <img class="emoji emoji2615" data-c="☕">
            <img class="emoji emoji1f375" data-c="🍵">
            <img class="emoji emoji1f376" data-c="🍶">
            <img class="emoji emoji1f37e" data-c="🍾">
            <img class="emoji emoji1f377" data-c="🍷">
            <img class="emoji emoji1f378" data-c="🍸">
            <img class="emoji emoji1f379" data-c="🍹">
            <img class="emoji emoji1f37a" data-c="🍺">
            <img class="emoji emoji1f37b" data-c="🍻">
            <img class="emoji emoji1f942" data-c="🥂">
            <img class="emoji emoji1f943" data-c="🥃">
            <img class="emoji emoji1f964" data-c="🥤">
            <img class="emoji emoji1f962" data-c="🥢">
            <img class="emoji emoji1f37d" data-c="🍽">
            <img class="emoji emoji1f374" data-c="🍴">
            <img class="emoji emoji1f944" data-c="🥄">
            <img class="emoji emoji1f52a" data-c="🔪">
            <img class="emoji emoji1f3fa" data-c="🏺">
        </div>
    </div>
</div>
</div>
<div class="m-l-10 m-t-10">
    <div class="btn-group dropup">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <img class="emoji emoji1f3c7" data-c="" data-r="1">
    </button>
    <div class="dropdown-menu dropdown-menu-left">
        <div class="dropdown-item row col-12 fbmoti">
            <img class="emoji emoji1f383" data-c="🎃">
            <img class="emoji emoji1f384" data-c="🎄">
            <img class="emoji emoji1f386" data-c="🎆">
            <img class="emoji emoji1f387" data-c="🎇">
            <img class="emoji emoji2728" data-c="✨">
            <img class="emoji emoji1f388" data-c="🎈">
            <img class="emoji emoji1f389" data-c="🎉">
            <img class="emoji emoji1f38a" data-c="🎊">
            <img class="emoji emoji1f38b" data-c="🎋">
            <img class="emoji emoji1f38d" data-c="🎍">
            <img class="emoji emoji1f38e" data-c="🎎">
            <img class="emoji emoji1f38f" data-c="🎏">
            <img class="emoji emoji1f390" data-c="🎐">
            <img class="emoji emoji1f391" data-c="🎑">
            <img class="emoji emoji1f380" data-c="🎀">
            <img class="emoji emoji1f381" data-c="🎁">
            <img class="emoji emoji1f397" data-c="🎗">
            <img class="emoji emoji1f39f" data-c="🎟">
            <img class="emoji emoji1f3ab" data-c="🎫">
            <img class="emoji emoji1f396" data-c="🎖">
            <img class="emoji emoji1f3c6" data-c="🏆">
            <img class="emoji emoji1f3c5" data-c="🏅">
            <img class="emoji emoji1f947" data-c="🥇">
            <img class="emoji emoji1f948" data-c="🥈">
            <img class="emoji emoji1f949" data-c="🥉">
            <img class="emoji emoji26bd" data-c="⚽">
            <img class="emoji emoji26be" data-c="⚾">
            <img class="emoji emoji1f3c0" data-c="🏀">
            <img class="emoji emoji1f3d0" data-c="🏐">
            <img class="emoji emoji1f3c8" data-c="🏈">
            <img class="emoji emoji1f3c9" data-c="🏉">
            <img class="emoji emoji1f3be" data-c="🎾">
            <img class="emoji emoji1f3b1" data-c="🎱">
            <img class="emoji emoji1f3b3" data-c="🎳">
            <img class="emoji emoji1f3cf" data-c="🏏">
            <img class="emoji emoji1f3d1" data-c="🏑">
            <img class="emoji emoji1f3d2" data-c="🏒">
            <img class="emoji emoji1f3d3" data-c="🏓">
            <img class="emoji emoji1f3f8" data-c="🏸">
            <img class="emoji emoji1f94a" data-c="🥊">
            <img class="emoji emoji1f94b" data-c="🥋">
            <img class="emoji emoji1f945" data-c="🥅">
            <img class="emoji emoji1f3af" data-c="🎯">
            <img class="emoji emoji26f3" data-c="⛳">
            <img class="emoji emoji26f8" data-c="⛸">
            <img class="emoji emoji1f3a3" data-c="🎣">
            <img class="emoji emoji1f3bd" data-c="🎽">
            <img class="emoji emoji1f3bf" data-c="🎿">
            <img class="emoji emoji1f6f7" data-c="🛷">
            <img class="emoji emoji1f94c" data-c="🥌">
            <img class="emoji emoji1f3ae" data-c="🎮">
            <img class="emoji emoji1f579" data-c="🕹">
            <img class="emoji emoji1f3b2" data-c="🎲">
            <img class="emoji emoji2660" data-c="♠">
            <img class="emoji emoji2665" data-c="♥">
            <img class="emoji emoji2666" data-c="♦">
            <img class="emoji emoji2663" data-c="♣">
            <img class="emoji emoji1f0cf" data-c="🃏">
            <img class="emoji emoji1f004" data-c="🀄">
            <img class="emoji emoji1f3b4" data-c="🎴">
            <img class="emoji emoji1f93a" data-c="🤺">
            <img class="emoji emoji1f3c7" data-c="🏇">
            <img class="emoji emoji26f7" data-c="⛷">
            <img class="emoji emoji1f3c2" data-c="🏂">
            <img class="emoji emoji1f3cc-200d-2642" data-c="🏌‍♂">
            <img class="emoji emoji1f3cc-200d-2640" data-c="🏌‍♀">
            <img class="emoji emoji1f3c4-200d-2642" data-c="🏄‍♂">
            <img class="emoji emoji1f3c4-200d-2640" data-c="🏄‍♀">
            <img class="emoji emoji1f6a3-200d-2642" data-c="🚣‍♂">
            <img class="emoji emoji1f6a3-200d-2640" data-c="🚣‍♀">
            <img class="emoji emoji1f3ca-200d-2642" data-c="🏊‍♂">
            <img class="emoji emoji1f3ca-200d-2640" data-c="🏊‍♀">
            <img class="emoji emoji26f9-200d-2642" data-c="⛹‍♂">
            <img class="emoji emoji26f9-200d-2640" data-c="⛹‍♀">
            <img class="emoji emoji1f3cb-200d-2642" data-c="🏋‍♂">
            <img class="emoji emoji1f3cb-200d-2640" data-c="🏋‍♀">
            <img class="emoji emoji1f6b4-200d-2642" data-c="🚴‍♂">
            <img class="emoji emoji1f6b4-200d-2640" data-c="🚴‍♀">
            <img class="emoji emoji1f6b5-200d-2642" data-c="🚵‍♂">
            <img class="emoji emoji1f6b5-200d-2640" data-c="🚵‍♀">
            <img class="emoji emoji1f3ce" data-c="🏎">
            <img class="emoji emoji1f3cd" data-c="🏍">
            <img class="emoji emoji1f938-200d-2642" data-c="🤸‍♂">
            <img class="emoji emoji1f938-200d-2640" data-c="🤸‍♀">
            <img class="emoji emoji1f93c-200d-2642" data-c="🤼‍♂">
            <img class="emoji emoji1f93c-200d-2640" data-c="🤼‍♀">
            <img class="emoji emoji1f93d-200d-2642" data-c="🤽‍♂">
            <img class="emoji emoji1f93d-200d-2640" data-c="🤽‍♀">
            <img class="emoji emoji1f93e-200d-2642" data-c="🤾‍♂">
            <img class="emoji emoji1f93e-200d-2640" data-c="🤾‍♀">
            <img class="emoji emoji1f939" data-c="🤹">
            <img class="emoji emoji1f9d7-200d-2640" data-c="🧗‍♀">
            <img class="emoji emoji1f9d7-200d-2642" data-c="🧗‍♂">
            <img class="emoji emoji1f9d8-200d-2640" data-c="🧘‍♀">
            <img class="emoji emoji1f9d8-200d-2642" data-c="🧘‍♂">
            <img class="emoji emoji1f468-200d-2695" data-c="👨‍⚕">
            <img class="emoji emoji1f469-200d-2695" data-c="👩‍⚕">
            <img class="emoji emoji1f468-200d-1f393" data-c="👨‍🎓">
            <img class="emoji emoji1f469-200d-1f393" data-c="👩‍🎓">
            <img class="emoji emoji1f468-200d-1f3eb" data-c="👨‍🏫">
            <img class="emoji emoji1f469-200d-1f3eb" data-c="👩‍🏫">
            <img class="emoji emoji1f468-200d-2696" data-c="👨‍⚖">
            <img class="emoji emoji1f469-200d-2696" data-c="👩‍⚖">
            <img class="emoji emoji1f468-200d-1f33e" data-c="👨‍🌾">
            <img class="emoji emoji1f469-200d-1f33e" data-c="👩‍🌾">
            <img class="emoji emoji1f468-200d-1f373" data-c="👨‍🍳">
            <img class="emoji emoji1f469-200d-1f373" data-c="👩‍🍳">
            <img class="emoji emoji1f468-200d-1f527" data-c="👨‍🔧">
            <img class="emoji emoji1f469-200d-1f527" data-c="👩‍🔧">
            <img class="emoji emoji1f468-200d-1f3ed" data-c="👨‍🏭">
            <img class="emoji emoji1f469-200d-1f3ed" data-c="👩‍🏭">
            <img class="emoji emoji1f468-200d-1f4bc" data-c="👨‍💼">
            <img class="emoji emoji1f469-200d-1f4bc" data-c="👩‍💼">
            <img class="emoji emoji1f468-200d-1f52c" data-c="👨‍🔬">
            <img class="emoji emoji1f469-200d-1f52c" data-c="👩‍🔬">
            <img class="emoji emoji1f468-200d-1f4bb" data-c="👨‍💻">
            <img class="emoji emoji1f469-200d-1f4bb" data-c="👩‍💻">
            <img class="emoji emoji1f468-200d-1f3a4" data-c="👨‍🎤">
            <img class="emoji emoji1f469-200d-1f3a4" data-c="👩‍🎤">
            <img class="emoji emoji1f468-200d-1f3a8" data-c="👨‍🎨">
            <img class="emoji emoji1f469-200d-1f3a8" data-c="👩‍🎨">
            <img class="emoji emoji1f468-200d-2708" data-c="👨‍✈">
            <img class="emoji emoji1f469-200d-2708" data-c="👩‍✈">
            <img class="emoji emoji1f468-200d-1f680" data-c="👨‍🚀">
            <img class="emoji emoji1f469-200d-1f680" data-c="👩‍🚀">
            <img class="emoji emoji1f468-200d-1f692" data-c="👨‍🚒">
            <img class="emoji emoji1f469-200d-1f692" data-c="👩‍🚒">
            <img class="emoji emoji1f46e-200d-2642" data-c="👮‍♂">
            <img class="emoji emoji1f46e-200d-2640" data-c="👮‍♀">
            <img class="emoji emoji1f575-200d-2642" data-c="🕵‍♂">
            <img class="emoji emoji1f575-200d-2640" data-c="🕵‍♀">
            <img class="emoji emoji1f482-200d-2642" data-c="💂‍♂">
            <img class="emoji emoji1f482-200d-2640" data-c="💂‍♀">
            <img class="emoji emoji1f477-200d-2642" data-c="👷‍♂">
            <img class="emoji emoji1f477-200d-2640" data-c="👷‍♀">
            <img class="emoji emoji1f468-200d-1f469-200d-1f466" data-c="👨‍👩‍👦">
            <img class="emoji emoji1f468-200d-1f469-200d-1f467" data-c="👨‍👩‍👧">
            <img class="emoji emoji1f468-200d-1f469-200d-1f467-200d-1f466" data-c="👨‍👩‍👧‍👦">
            <img class="emoji emoji1f468-200d-1f469-200d-1f466-200d-1f466" data-c="👨‍👩‍👦‍👦">
            <img class="emoji emoji1f468-200d-1f469-200d-1f467-200d-1f467" data-c="👨‍👩‍👧‍👧">
            <img class="emoji emoji1f468-200d-1f468-200d-1f466" data-c="👨‍👨‍👦">
            <img class="emoji emoji1f468-200d-1f468-200d-1f467" data-c="👨‍👨‍👧">
            <img class="emoji emoji1f468-200d-1f468-200d-1f467-200d-1f466" data-c="👨‍👨‍👧‍👦">
            <img class="emoji emoji1f468-200d-1f468-200d-1f466-200d-1f466" data-c="👨‍👨‍👦‍👦">
            <img class="emoji emoji1f468-200d-1f468-200d-1f467-200d-1f467" data-c="👨‍👨‍👧‍👧">
            <img class="emoji emoji1f469-200d-1f469-200d-1f466" data-c="👩‍👩‍👦">
            <img class="emoji emoji1f469-200d-1f469-200d-1f467" data-c="👩‍👩‍👧">
            <img class="emoji emoji1f469-200d-1f469-200d-1f467-200d-1f466" data-c="👩‍👩‍👧‍👦">
            <img class="emoji emoji1f469-200d-1f469-200d-1f466-200d-1f466" data-c="👩‍👩‍👦‍👦">
            <img class="emoji emoji1f469-200d-1f469-200d-1f467-200d-1f467" data-c="👩‍👩‍👧‍👧">
            <img class="emoji emoji1f468-200d-1f466" data-c="👨‍👦">
            <img class="emoji emoji1f468-200d-1f466-200d-1f466" data-c="👨‍👦‍👦">
            <img class="emoji emoji1f468-200d-1f467" data-c="👨‍👧">
            <img class="emoji emoji1f468-200d-1f467-200d-1f466" data-c="👨‍👧‍👦">
            <img class="emoji emoji1f468-200d-1f467-200d-1f467" data-c="👨‍👧‍👧">
            <img class="emoji emoji1f469-200d-1f466" data-c="👩‍👦">
            <img class="emoji emoji1f469-200d-1f466-200d-1f466" data-c="👩‍👦‍👦">
            <img class="emoji emoji1f469-200d-1f467" data-c="👩‍👧">
            <img class="emoji emoji1f469-200d-1f467-200d-1f466" data-c="👩‍👧‍👦">
            <img class="emoji emoji1f469-200d-1f467-200d-1f467" data-c="👩‍👧‍👧">
        </div>
    </div>
</div>
</div>
<div class="m-l-10 m-t-10">
    <div class="btn-group dropup">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <img class="emoji emoji1f3a0" data-c="" data-r="1">
    </button>
    <div class="dropdown-menu dropdown-menu-left">
        <div class="dropdown-item row col-12 fbmoti">
            <img class="emoji emoji1f30d" data-c="🌍">
            <img class="emoji emoji1f30e" data-c="🌎">
            <img class="emoji emoji1f30f" data-c="🌏">
            <img class="emoji emoji1f310" data-c="🌐">
            <img class="emoji emoji1f5fa" data-c="🗺">
            <img class="emoji emoji1f5fe" data-c="🗾">
            <img class="emoji emoji1f3d4" data-c="🏔">
            <img class="emoji emoji26f0" data-c="⛰">
            <img class="emoji emoji1f30b" data-c="🌋">
            <img class="emoji emoji1f5fb" data-c="🗻">
            <img class="emoji emoji1f3d5" data-c="🏕">
            <img class="emoji emoji1f3d6" data-c="🏖">
            <img class="emoji emoji1f3dc" data-c="🏜">
            <img class="emoji emoji1f3dd" data-c="🏝">
            <img class="emoji emoji1f3de" data-c="🏞">
            <img class="emoji emoji1f3df" data-c="🏟">
            <img class="emoji emoji1f3db" data-c="🏛">
            <img class="emoji emoji1f3d7" data-c="🏗">
            <img class="emoji emoji1f3d8" data-c="🏘">
            <img class="emoji emoji1f3d9" data-c="🏙">
            <img class="emoji emoji1f3da" data-c="🏚">
            <img class="emoji emoji1f3e0" data-c="🏠">
            <img class="emoji emoji1f3e1" data-c="🏡">
            <img class="emoji emoji1f3e2" data-c="🏢">
            <img class="emoji emoji1f3e3" data-c="🏣">
            <img class="emoji emoji1f3e4" data-c="🏤">
            <img class="emoji emoji1f3e5" data-c="🏥">
            <img class="emoji emoji1f3e6" data-c="🏦">
            <img class="emoji emoji1f3e8" data-c="🏨">
            <img class="emoji emoji1f3e9" data-c="🏩">
            <img class="emoji emoji1f3ea" data-c="🏪">
            <img class="emoji emoji1f3eb" data-c="🏫">
            <img class="emoji emoji1f3ec" data-c="🏬">
            <img class="emoji emoji1f3ed" data-c="🏭">
            <img class="emoji emoji1f3ef" data-c="🏯">
            <img class="emoji emoji1f3f0" data-c="🏰">
            <img class="emoji emoji1f492" data-c="💒">
            <img class="emoji emoji1f5fc" data-c="🗼">
            <img class="emoji emoji1f5fd" data-c="🗽">
            <img class="emoji emoji26ea" data-c="⛪">
            <img class="emoji emoji1f54c" data-c="🕌">
            <img class="emoji emoji1f54d" data-c="🕍">
            <img class="emoji emoji26e9" data-c="⛩">
            <img class="emoji emoji1f54b" data-c="🕋">
            <img class="emoji emoji26f2" data-c="⛲">
            <img class="emoji emoji26fa" data-c="⛺">
            <img class="emoji emoji1f301" data-c="🌁">
            <img class="emoji emoji1f303" data-c="🌃">
            <img class="emoji emoji1f304" data-c="🌄">
            <img class="emoji emoji1f305" data-c="🌅">
            <img class="emoji emoji1f306" data-c="🌆">
            <img class="emoji emoji1f307" data-c="🌇">
            <img class="emoji emoji1f309" data-c="🌉">
            <img class="emoji emoji2668" data-c="♨">
            <img class="emoji emoji1f30c" data-c="🌌">
            <img class="emoji emoji1f3a0" data-c="🎠">
            <img class="emoji emoji1f3a1" data-c="🎡">
            <img class="emoji emoji1f3a2" data-c="🎢">
            <img class="emoji emoji1f488" data-c="💈">
            <img class="emoji emoji1f3aa" data-c="🎪">
            <img class="emoji emoji1f3ad" data-c="🎭">
            <img class="emoji emoji1f5bc" data-c="🖼">
            <img class="emoji emoji1f3a8" data-c="🎨">
            <img class="emoji emoji1f3b0" data-c="🎰">
            <img class="emoji emoji1f682" data-c="🚂">
            <img class="emoji emoji1f683" data-c="🚃">
            <img class="emoji emoji1f684" data-c="🚄">
            <img class="emoji emoji1f685" data-c="🚅">
            <img class="emoji emoji1f686" data-c="🚆">
            <img class="emoji emoji1f687" data-c="🚇">
            <img class="emoji emoji1f688" data-c="🚈">
            <img class="emoji emoji1f689" data-c="🚉">
            <img class="emoji emoji1f68a" data-c="🚊">
            <img class="emoji emoji1f69d" data-c="🚝">
            <img class="emoji emoji1f69e" data-c="🚞">
            <img class="emoji emoji1f68b" data-c="🚋">
            <img class="emoji emoji1f68c" data-c="🚌">
            <img class="emoji emoji1f68d" data-c="🚍">
            <img class="emoji emoji1f68e" data-c="🚎">
            <img class="emoji emoji1f690" data-c="🚐">
            <img class="emoji emoji1f691" data-c="🚑">
            <img class="emoji emoji1f692" data-c="🚒">
            <img class="emoji emoji1f693" data-c="🚓">
            <img class="emoji emoji1f694" data-c="🚔">
            <img class="emoji emoji1f695" data-c="🚕">
            <img class="emoji emoji1f696" data-c="🚖">
            <img class="emoji emoji1f697" data-c="🚗">
            <img class="emoji emoji1f698" data-c="🚘">
            <img class="emoji emoji1f699" data-c="🚙">
            <img class="emoji emoji1f69a" data-c="🚚">
            <img class="emoji emoji1f69b" data-c="🚛">
            <img class="emoji emoji1f69c" data-c="🚜">
            <img class="emoji emoji1f6b2" data-c="🚲">
            <img class="emoji emoji1f6f4" data-c="🛴">
            <img class="emoji emoji1f6f5" data-c="🛵">
            <img class="emoji emoji1f68f" data-c="🚏">
            <img class="emoji emoji1f6e3" data-c="🛣">
            <img class="emoji emoji1f6e4" data-c="🛤">
            <img class="emoji emoji26fd" data-c="⛽">
            <img class="emoji emoji1f6a8" data-c="🚨">
            <img class="emoji emoji1f6a5" data-c="🚥">
            <img class="emoji emoji1f6a6" data-c="🚦">
            <img class="emoji emoji1f6a7" data-c="🚧">
            <img class="emoji emoji1f6d1" data-c="🛑">
            <img class="emoji emoji2693" data-c="⚓">
            <img class="emoji emoji26f5" data-c="⛵">
            <img class="emoji emoji1f6f6" data-c="🛶">
            <img class="emoji emoji1f6a4" data-c="🚤">
            <img class="emoji emoji1f6f3" data-c="🛳">
            <img class="emoji emoji26f4" data-c="⛴">
            <img class="emoji emoji1f6e5" data-c="🛥">
            <img class="emoji emoji1f6a2" data-c="🚢">
            <img class="emoji emoji2708" data-c="✈">
            <img class="emoji emoji1f6e9" data-c="🛩">
            <img class="emoji emoji1f6eb" data-c="🛫">
            <img class="emoji emoji1f6ec" data-c="🛬">
            <img class="emoji emoji1f4ba" data-c="💺">
            <img class="emoji emoji1f681" data-c="🚁">
            <img class="emoji emoji1f69f" data-c="🚟">
            <img class="emoji emoji1f6a0" data-c="🚠">
            <img class="emoji emoji1f6a1" data-c="🚡">
            <img class="emoji emoji1f6f0" data-c="🛰">
            <img class="emoji emoji1f680" data-c="🚀">
            <img class="emoji emoji1f6f8" data-c="🛸">
            <img class="emoji emoji1f6ce" data-c="🛎">
            <img class="emoji emoji1f6aa" data-c="🚪">
            <img class="emoji emoji1f6cf" data-c="🛏">
            <img class="emoji emoji1f6cb" data-c="🛋">
            <img class="emoji emoji1f6bd" data-c="🚽">
            <img class="emoji emoji1f6bf" data-c="🚿">
            <img class="emoji emoji1f6c1" data-c="🛁">
            <img class="emoji emoji231b" data-c="⌛">
            <img class="emoji emoji23f3" data-c="⏳">
            <img class="emoji emoji231a" data-c="⌚">
            <img class="emoji emoji23f0" data-c="⏰">
            <img class="emoji emoji23f1" data-c="⏱">
            <img class="emoji emoji23f2" data-c="⏲">
            <img class="emoji emoji1f570" data-c="🕰">
            <img class="emoji emoji1f55b" data-c="🕛">
            <img class="emoji emoji1f567" data-c="🕧">
            <img class="emoji emoji1f550" data-c="🕐">
            <img class="emoji emoji1f55c" data-c="🕜">
            <img class="emoji emoji1f551" data-c="🕑">
            <img class="emoji emoji1f55d" data-c="🕝">
            <img class="emoji emoji1f552" data-c="🕒">
            <img class="emoji emoji1f55e" data-c="🕞">
            <img class="emoji emoji1f553" data-c="🕓">
            <img class="emoji emoji1f55f" data-c="🕟">
            <img class="emoji emoji1f554" data-c="🕔">
            <img class="emoji emoji1f560" data-c="🕠">
            <img class="emoji emoji1f555" data-c="🕕">
            <img class="emoji emoji1f561" data-c="🕡">
            <img class="emoji emoji1f556" data-c="🕖">
            <img class="emoji emoji1f562" data-c="🕢">
            <img class="emoji emoji1f557" data-c="🕗">
            <img class="emoji emoji1f563" data-c="🕣">
            <img class="emoji emoji1f558" data-c="🕘">
            <img class="emoji emoji1f564" data-c="🕤">
            <img class="emoji emoji1f559" data-c="🕙">
            <img class="emoji emoji1f565" data-c="🕥">
            <img class="emoji emoji1f55a" data-c="🕚">
            <img class="emoji emoji1f566" data-c="🕦">
            <img class="emoji emoji1f311" data-c="🌑">
            <img class="emoji emoji1f312" data-c="🌒">
            <img class="emoji emoji1f313" data-c="🌓">
            <img class="emoji emoji1f314" data-c="🌔">
            <img class="emoji emoji1f315" data-c="🌕">
            <img class="emoji emoji1f316" data-c="🌖">
            <img class="emoji emoji1f317" data-c="🌗">
            <img class="emoji emoji1f318" data-c="🌘">
            <img class="emoji emoji1f319" data-c="🌙">
            <img class="emoji emoji1f31a" data-c="🌚">
            <img class="emoji emoji1f31b" data-c="🌛">
            <img class="emoji emoji1f31c" data-c="🌜">
            <img class="emoji emoji1f321" data-c="🌡">
            <img class="emoji emoji2600" data-c="☀">
            <img class="emoji emoji1f31d" data-c="🌝">
            <img class="emoji emoji1f31e" data-c="🌞">
            <img class="emoji emoji2b50" data-c="⭐">
            <img class="emoji emoji1f31f" data-c="🌟">
            <img class="emoji emoji1f320" data-c="🌠">
            <img class="emoji emoji2601" data-c="☁">
            <img class="emoji emoji26c5" data-c="⛅">
            <img class="emoji emoji26c8" data-c="⛈">
            <img class="emoji emoji1f324" data-c="🌤">
            <img class="emoji emoji1f325" data-c="🌥">
            <img class="emoji emoji1f326" data-c="🌦">
            <img class="emoji emoji1f327" data-c="🌧">
            <img class="emoji emoji1f328" data-c="🌨">
            <img class="emoji emoji1f329" data-c="🌩">
            <img class="emoji emoji1f32a" data-c="🌪">
            <img class="emoji emoji1f32b" data-c="🌫">
            <img class="emoji emoji1f32c" data-c="🌬">
            <img class="emoji emoji1f300" data-c="🌀">
            <img class="emoji emoji1f308" data-c="🌈">
            <img class="emoji emoji1f302" data-c="🌂">
            <img class="emoji emoji2602" data-c="☂">
            <img class="emoji emoji2614" data-c="☔">
            <img class="emoji emoji26f1" data-c="⛱">
            <img class="emoji emoji26a1" data-c="⚡">
            <img class="emoji emoji2744" data-c="❄">
            <img class="emoji emoji2603" data-c="☃">
            <img class="emoji emoji26c4" data-c="⛄">
            <img class="emoji emoji2604" data-c="☄">
            <img class="emoji emoji1f525" data-c="🔥">
            <img class="emoji emoji1f4a7" data-c="💧">
            <img class="emoji emoji1f30a" data-c="🌊">
        </div>
    </div>
</div>
</div>
<div class="m-l-10 m-t-10">
    <div class="btn-group dropup">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <img class="emoji emoji1f4bc" data-c="" data-r="1">

    </button>
    <div class="dropdown-menu dropdown-menu-left">
        <div class="dropdown-item row col-12 fbmoti">
            <img class="emoji emoji1f507" data-c="🔇">
            <img class="emoji emoji1f508" data-c="🔈">
            <img class="emoji emoji1f509" data-c="🔉">
            <img class="emoji emoji1f50a" data-c="🔊">
            <img class="emoji emoji1f4e2" data-c="📢">
            <img class="emoji emoji1f4e3" data-c="📣">
            <img class="emoji emoji1f4ef" data-c="📯">
            <img class="emoji emoji1f514" data-c="🔔">
            <img class="emoji emoji1f515" data-c="🔕">
            <img class="emoji emoji1f3bc" data-c="🎼">
            <img class="emoji emoji1f3b5" data-c="🎵">
            <img class="emoji emoji1f3b6" data-c="🎶">
            <img class="emoji emoji1f399" data-c="🎙">
            <img class="emoji emoji1f39a" data-c="🎚">
            <img class="emoji emoji1f39b" data-c="🎛">
            <img class="emoji emoji1f3a4" data-c="🎤">
            <img class="emoji emoji1f3a7" data-c="🎧">
            <img class="emoji emoji1f4fb" data-c="📻">
            <img class="emoji emoji1f3b7" data-c="🎷">
            <img class="emoji emoji1f3b8" data-c="🎸">
            <img class="emoji emoji1f3b9" data-c="🎹">
            <img class="emoji emoji1f3ba" data-c="🎺">
            <img class="emoji emoji1f3bb" data-c="🎻">
            <img class="emoji emoji1f941" data-c="🥁">
            <img class="emoji emoji1f4f1" data-c="📱">
            <img class="emoji emoji1f4f2" data-c="📲">
            <img class="emoji emoji260e" data-c="☎">
            <img class="emoji emoji1f4de" data-c="📞">
            <img class="emoji emoji1f4df" data-c="📟">
            <img class="emoji emoji1f4e0" data-c="📠">
            <img class="emoji emoji1f50b" data-c="🔋">
            <img class="emoji emoji1f50c" data-c="🔌">
            <img class="emoji emoji1f4bb" data-c="💻">
            <img class="emoji emoji1f5a5" data-c="🖥">
            <img class="emoji emoji1f5a8" data-c="🖨">
            <img class="emoji emoji2328" data-c="⌨">
            <img class="emoji emoji1f5b1" data-c="🖱">
            <img class="emoji emoji1f5b2" data-c="🖲">
            <img class="emoji emoji1f4bd" data-c="💽">
            <img class="emoji emoji1f4be" data-c="💾">
            <img class="emoji emoji1f4bf" data-c="💿">
            <img class="emoji emoji1f4c0" data-c="📀">
            <img class="emoji emoji1f3a5" data-c="🎥">
            <img class="emoji emoji1f39e" data-c="🎞">
            <img class="emoji emoji1f4fd" data-c="📽">
            <img class="emoji emoji1f3ac" data-c="🎬">
            <img class="emoji emoji1f4fa" data-c="📺">
            <img class="emoji emoji1f4f7" data-c="📷">
            <img class="emoji emoji1f4f8" data-c="📸">
            <img class="emoji emoji1f4f9" data-c="📹">
            <img class="emoji emoji1f4fc" data-c="📼">
            <img class="emoji emoji1f50d" data-c="🔍">
            <img class="emoji emoji1f50e" data-c="🔎">
            <img class="emoji emoji1f52c" data-c="🔬">
            <img class="emoji emoji1f52d" data-c="🔭">
            <img class="emoji emoji1f4e1" data-c="📡">
            <img class="emoji emoji1f56f" data-c="🕯">
            <img class="emoji emoji1f4a1" data-c="💡">
            <img class="emoji emoji1f526" data-c="🔦">
            <img class="emoji emoji1f3ee" data-c="🏮">
            <img class="emoji emoji1f4d4" data-c="📔">
            <img class="emoji emoji1f4d5" data-c="📕">
            <img class="emoji emoji1f4d6" data-c="📖">
            <img class="emoji emoji1f4d7" data-c="📗">
            <img class="emoji emoji1f4d8" data-c="📘">
            <img class="emoji emoji1f4d9" data-c="📙">
            <img class="emoji emoji1f4da" data-c="📚">
            <img class="emoji emoji1f4d3" data-c="📓">
            <img class="emoji emoji1f4d2" data-c="📒">
            <img class="emoji emoji1f4c3" data-c="📃">
            <img class="emoji emoji1f4dc" data-c="📜">
            <img class="emoji emoji1f4c4" data-c="📄">
            <img class="emoji emoji1f4f0" data-c="📰">
            <img class="emoji emoji1f5de" data-c="🗞">
            <img class="emoji emoji1f4d1" data-c="📑">
            <img class="emoji emoji1f516" data-c="🔖">
            <img class="emoji emoji1f3f7" data-c="🏷">
            <img class="emoji emoji1f4b0" data-c="💰">
            <img class="emoji emoji1f4b4" data-c="💴">
            <img class="emoji emoji1f4b5" data-c="💵">
            <img class="emoji emoji1f4b6" data-c="💶">
            <img class="emoji emoji1f4b7" data-c="💷">
            <img class="emoji emoji1f4b8" data-c="💸">
            <img class="emoji emoji1f4b3" data-c="💳">
            <img class="emoji emoji1f4b9" data-c="💹">
            <img class="emoji emoji1f4b1" data-c="💱">
            <img class="emoji emoji1f4b2" data-c="💲">
            <img class="emoji emoji2709" data-c="✉">
            <img class="emoji emoji1f4e7" data-c="📧">
            <img class="emoji emoji1f4e8" data-c="📨">
            <img class="emoji emoji1f4e9" data-c="📩">
            <img class="emoji emoji1f4e4" data-c="📤">
            <img class="emoji emoji1f4e5" data-c="📥">
            <img class="emoji emoji1f4e6" data-c="📦">
            <img class="emoji emoji1f4eb" data-c="📫">
            <img class="emoji emoji1f4ea" data-c="📪">
            <img class="emoji emoji1f4ec" data-c="📬">
            <img class="emoji emoji1f4ed" data-c="📭">
            <img class="emoji emoji1f4ee" data-c="📮">
            <img class="emoji emoji1f5f3" data-c="🗳">
            <img class="emoji emoji270f" data-c="✏">
            <img class="emoji emoji2712" data-c="✒">
            <img class="emoji emoji1f58b" data-c="🖋">
            <img class="emoji emoji1f58a" data-c="🖊">
            <img class="emoji emoji1f58c" data-c="🖌">
            <img class="emoji emoji1f58d" data-c="🖍">
            <img class="emoji emoji1f4dd" data-c="📝">
            <img class="emoji emoji1f4bc" data-c="💼">
            <img class="emoji emoji1f4c1" data-c="📁">
            <img class="emoji emoji1f4c2" data-c="📂">
            <img class="emoji emoji1f5c2" data-c="🗂">
            <img class="emoji emoji1f4c5" data-c="📅">
            <img class="emoji emoji1f4c6" data-c="📆">
            <img class="emoji emoji1f5d2" data-c="🗒">
            <img class="emoji emoji1f5d3" data-c="🗓">
            <img class="emoji emoji1f4c7" data-c="📇">
            <img class="emoji emoji1f4c8" data-c="📈">
            <img class="emoji emoji1f4c9" data-c="📉">
            <img class="emoji emoji1f4ca" data-c="📊">
            <img class="emoji emoji1f4cb" data-c="📋">
            <img class="emoji emoji1f4cc" data-c="📌">
            <img class="emoji emoji1f4cd" data-c="📍">
            <img class="emoji emoji1f4ce" data-c="📎">
            <img class="emoji emoji1f587" data-c="🖇">
            <img class="emoji emoji1f4cf" data-c="📏">
            <img class="emoji emoji1f4d0" data-c="📐">
            <img class="emoji emoji2702" data-c="✂">
            <img class="emoji emoji1f5c3" data-c="🗃">
            <img class="emoji emoji1f5c4" data-c="🗄">
            <img class="emoji emoji1f5d1" data-c="🗑">
            <img class="emoji emoji1f512" data-c="🔒">
            <img class="emoji emoji1f513" data-c="🔓">
            <img class="emoji emoji1f50f" data-c="🔏">
            <img class="emoji emoji1f510" data-c="🔐">
            <img class="emoji emoji1f511" data-c="🔑">
            <img class="emoji emoji1f5dd" data-c="🗝">
            <img class="emoji emoji1f528" data-c="🔨">
            <img class="emoji emoji26cf" data-c="⛏">
            <img class="emoji emoji2692" data-c="⚒">
            <img class="emoji emoji1f6e0" data-c="🛠">
            <img class="emoji emoji1f5e1" data-c="🗡">
            <img class="emoji emoji2694" data-c="⚔">
            <img class="emoji emoji1f52b" data-c="🔫">
            <img class="emoji emoji1f3f9" data-c="🏹">
            <img class="emoji emoji1f6e1" data-c="🛡">
            <img class="emoji emoji1f527" data-c="🔧">
            <img class="emoji emoji1f529" data-c="🔩">
            <img class="emoji emoji2699" data-c="⚙">
            <img class="emoji emoji1f5dc" data-c="🗜">
            <img class="emoji emoji2697" data-c="⚗">
            <img class="emoji emoji2696" data-c="⚖">
            <img class="emoji emoji1f517" data-c="🔗">
            <img class="emoji emoji26d3" data-c="⛓">
            <img class="emoji emoji1f489" data-c="💉">
            <img class="emoji emoji1f48a" data-c="💊">
            <img class="emoji emoji1f6ac" data-c="🚬">
            <img class="emoji emoji26b0" data-c="⚰">
            <img class="emoji emoji26b1" data-c="⚱">
            <img class="emoji emoji1f5ff" data-c="🗿">
            <img class="emoji emoji1f6e2" data-c="🛢">
            <img class="emoji emoji1f52e" data-c="🔮">
            <img class="emoji emoji1f6d2" data-c="🛒">
            <img class="emoji emoji1f453" data-c="👓">
            <img class="emoji emoji1f576" data-c="🕶">
            <img class="emoji emoji1f454" data-c="👔">
            <img class="emoji emoji1f455" data-c="👕">
            <img class="emoji emoji1f456" data-c="👖">
            <img class="emoji emoji1f9e3" data-c="🧣">
            <img class="emoji emoji1f9e4" data-c="🧤">
            <img class="emoji emoji1f9e5" data-c="🧥">
            <img class="emoji emoji1f9e6" data-c="🧦">
            <img class="emoji emoji1f457" data-c="👗">
            <img class="emoji emoji1f458" data-c="👘">
            <img class="emoji emoji1f459" data-c="👙">
            <img class="emoji emoji1f45a" data-c="👚">
            <img class="emoji emoji1f45b" data-c="👛">
            <img class="emoji emoji1f45c" data-c="👜">
            <img class="emoji emoji1f45d" data-c="👝">
            <img class="emoji emoji1f6cd" data-c="🛍">
            <img class="emoji emoji1f392" data-c="🎒">
            <img class="emoji emoji1f45e" data-c="👞">
            <img class="emoji emoji1f45f" data-c="👟">
            <img class="emoji emoji1f460" data-c="👠">
            <img class="emoji emoji1f461" data-c="👡">
            <img class="emoji emoji1f462" data-c="👢">
            <img class="emoji emoji1f451" data-c="👑">
            <img class="emoji emoji1f452" data-c="👒">
            <img class="emoji emoji1f3a9" data-c="🎩">
            <img class="emoji emoji1f393" data-c="🎓">
            <img class="emoji emoji1f9e2" data-c="🧢">
            <img class="emoji emoji26d1" data-c="⛑">
            <img class="emoji emoji1f4ff" data-c="📿">
            <img class="emoji emoji1f484" data-c="💄">
            <img class="emoji emoji1f48d" data-c="💍">
            <img class="emoji emoji1f48e" data-c="💎">
        </div>
    </div>
</div>
</div>
<div class="m-l-10 m-t-10">
    <div class="btn-group dropup">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <img class="emoji emoji1f4a0" data-c="" data-r="1">

    </button>
    <div class="dropdown-menu dropdown-menu-left">
        <div class="dropdown-item row col-12 fbmoti">
            <img class="emoji emoji1f3e7" data-c="🏧">
            <img class="emoji emoji1f6ae" data-c="🚮">
            <img class="emoji emoji1f6b0" data-c="🚰">
            <img class="emoji emoji267f" data-c="♿">
            <img class="emoji emoji1f6b9" data-c="🚹">
            <img class="emoji emoji1f6ba" data-c="🚺">
            <img class="emoji emoji1f6bb" data-c="🚻">
            <img class="emoji emoji1f6bc" data-c="🚼">
            <img class="emoji emoji1f6be" data-c="🚾">
            <img class="emoji emoji1f6c2" data-c="🛂">
            <img class="emoji emoji1f6c3" data-c="🛃">
            <img class="emoji emoji1f6c4" data-c="🛄">
            <img class="emoji emoji1f6c5" data-c="🛅">
            <img class="emoji emoji26a0" data-c="⚠">
            <img class="emoji emoji1f6b8" data-c="🚸">
            <img class="emoji emoji26d4" data-c="⛔">
            <img class="emoji emoji1f6ab" data-c="🚫">
            <img class="emoji emoji1f6b3" data-c="🚳">
            <img class="emoji emoji1f6ad" data-c="🚭">
            <img class="emoji emoji1f6af" data-c="🚯">
            <img class="emoji emoji1f6b1" data-c="🚱">
            <img class="emoji emoji1f6b7" data-c="🚷">
            <img class="emoji emoji1f4f5" data-c="📵">
            <img class="emoji emoji1f51e" data-c="🔞">
            <img class="emoji emoji2622" data-c="☢">
            <img class="emoji emoji2623" data-c="☣">
            <img class="emoji emoji2b06" data-c="⬆">
            <img class="emoji emoji2197" data-c="↗">
            <img class="emoji emoji27a1" data-c="➡">
            <img class="emoji emoji2198" data-c="↘">
            <img class="emoji emoji2b07" data-c="⬇">
            <img class="emoji emoji2199" data-c="↙">
            <img class="emoji emoji2b05" data-c="⬅">
            <img class="emoji emoji2196" data-c="↖">
            <img class="emoji emoji2195" data-c="↕">
            <img class="emoji emoji2194" data-c="↔">
            <img class="emoji emoji21a9" data-c="↩">
            <img class="emoji emoji21aa" data-c="↪">
            <img class="emoji emoji2934" data-c="⤴">
            <img class="emoji emoji2935" data-c="⤵">
            <img class="emoji emoji1f503" data-c="🔃">
            <img class="emoji emoji1f504" data-c="🔄">
            <img class="emoji emoji1f519" data-c="🔙">
            <img class="emoji emoji1f51a" data-c="🔚">
            <img class="emoji emoji1f51b" data-c="🔛">
            <img class="emoji emoji1f51c" data-c="🔜">
            <img class="emoji emoji1f51d" data-c="🔝">
            <img class="emoji emoji1f6d0" data-c="🛐">
            <img class="emoji emoji269b" data-c="⚛">
            <img class="emoji emoji1f549" data-c="🕉">
            <img class="emoji emoji2721" data-c="✡">
            <img class="emoji emoji2638" data-c="☸">
            <img class="emoji emoji262f" data-c="☯">
            <img class="emoji emoji271d" data-c="✝">
            <img class="emoji emoji2626" data-c="☦">
            <img class="emoji emoji262a" data-c="☪">
            <img class="emoji emoji262e" data-c="☮">
            <img class="emoji emoji1f54e" data-c="🕎">
            <img class="emoji emoji1f52f" data-c="🔯">
            <img class="emoji emoji2648" data-c="♈">
            <img class="emoji emoji2649" data-c="♉">
            <img class="emoji emoji264a" data-c="♊">
            <img class="emoji emoji264b" data-c="♋">
            <img class="emoji emoji264c" data-c="♌">
            <img class="emoji emoji264d" data-c="♍">
            <img class="emoji emoji264e" data-c="♎">
            <img class="emoji emoji264f" data-c="♏">
            <img class="emoji emoji2650" data-c="♐">
            <img class="emoji emoji2651" data-c="♑">
            <img class="emoji emoji2652" data-c="♒">
            <img class="emoji emoji2653" data-c="♓">
            <img class="emoji emoji26ce" data-c="⛎">
            <img class="emoji emoji1f500" data-c="🔀">
            <img class="emoji emoji1f501" data-c="🔁">
            <img class="emoji emoji1f502" data-c="🔂">
            <img class="emoji emoji25b6" data-c="▶">
            <img class="emoji emoji23e9" data-c="⏩">
            <img class="emoji emoji23ed" data-c="⏭">
            <img class="emoji emoji23ef" data-c="⏯">
            <img class="emoji emoji25c0" data-c="◀">
            <img class="emoji emoji23ea" data-c="⏪">
            <img class="emoji emoji23ee" data-c="⏮">
            <img class="emoji emoji1f53c" data-c="🔼">
            <img class="emoji emoji23eb" data-c="⏫">
            <img class="emoji emoji1f53d" data-c="🔽">
            <img class="emoji emoji23ec" data-c="⏬">
            <img class="emoji emoji23f8" data-c="⏸">
            <img class="emoji emoji23f9" data-c="⏹">
            <img class="emoji emoji23fa" data-c="⏺">
            <img class="emoji emoji23cf" data-c="⏏">
            <img class="emoji emoji1f3a6" data-c="🎦">
            <img class="emoji emoji1f505" data-c="🔅">
            <img class="emoji emoji1f506" data-c="🔆">
            <img class="emoji emoji1f4f6" data-c="📶">
            <img class="emoji emoji1f4f3" data-c="📳">
            <img class="emoji emoji1f4f4" data-c="📴">
            <img class="emoji emoji2640" data-c="♀">
            <img class="emoji emoji2642" data-c="♂">
            <img class="emoji emoji2695" data-c="⚕">
            <img class="emoji emoji267b" data-c="♻">
            <img class="emoji emoji269c" data-c="⚜">
            <img class="emoji emoji1f531" data-c="🔱">
            <img class="emoji emoji1f4db" data-c="📛">
            <img class="emoji emoji1f530" data-c="🔰">
            <img class="emoji emoji2b55" data-c="⭕">
            <img class="emoji emoji2705" data-c="✅">
            <img class="emoji emoji2611" data-c="☑">
            <img class="emoji emoji2714" data-c="✔">
            <img class="emoji emoji2716" data-c="✖">
            <img class="emoji emoji274c" data-c="❌">
            <img class="emoji emoji274e" data-c="❎">
            <img class="emoji emoji2795" data-c="➕">
            <img class="emoji emoji2796" data-c="➖">
            <img class="emoji emoji2797" data-c="➗">
            <img class="emoji emoji27b0" data-c="➰">
            <img class="emoji emoji27bf" data-c="➿">
            <img class="emoji emoji303d" data-c="〽">
            <img class="emoji emoji2733" data-c="✳">
            <img class="emoji emoji2734" data-c="✴">
            <img class="emoji emoji2747" data-c="❇">
            <img class="emoji emoji203c" data-c="‼">
            <img class="emoji emoji2049" data-c="⁉">
            <img class="emoji emoji2753" data-c="❓">
            <img class="emoji emoji2754" data-c="❔">
            <img class="emoji emoji2755" data-c="❕">
            <img class="emoji emoji2757" data-c="❗">
            <img class="emoji emoji3030" data-c="〰">
            <img class="emoji emojia9" data-c="©">
            <img class="emoji emojiae" data-c="®">
            <img class="emoji emoji2122" data-c="™">
            <img class="emoji emoji23-20e3" data-c="#⃣">
            <img class="emoji emoji2a-20e3" data-c="*⃣">
            <img class="emoji emoji30-20e3" data-c="0⃣">
            <img class="emoji emoji31-20e3" data-c="1⃣">
            <img class="emoji emoji32-20e3" data-c="2⃣">
            <img class="emoji emoji33-20e3" data-c="3⃣">
            <img class="emoji emoji34-20e3" data-c="4⃣">
            <img class="emoji emoji35-20e3" data-c="5⃣">
            <img class="emoji emoji36-20e3" data-c="6⃣">
            <img class="emoji emoji37-20e3" data-c="7⃣">
            <img class="emoji emoji38-20e3" data-c="8⃣">
            <img class="emoji emoji39-20e3" data-c="9⃣">
            <img class="emoji emoji1f51f" data-c="🔟">
            <img class="emoji emoji1f4af" data-c="💯">
            <img class="emoji emoji1f520" data-c="🔠">
            <img class="emoji emoji1f521" data-c="🔡">
            <img class="emoji emoji1f522" data-c="🔢">
            <img class="emoji emoji1f523" data-c="🔣">
            <img class="emoji emoji1f524" data-c="🔤">
            <img class="emoji emoji1f170" data-c="🅰">
            <img class="emoji emoji1f18e" data-c="🆎">
            <img class="emoji emoji1f171" data-c="🅱">
            <img class="emoji emoji1f191" data-c="🆑">
            <img class="emoji emoji1f192" data-c="🆒">
            <img class="emoji emoji1f193" data-c="🆓">
            <img class="emoji emoji2139" data-c="ℹ">
            <img class="emoji emoji1f194" data-c="🆔">
            <img class="emoji emoji24c2" data-c="Ⓜ">
            <img class="emoji emoji1f195" data-c="🆕">
            <img class="emoji emoji1f196" data-c="🆖">
            <img class="emoji emoji1f17e" data-c="🅾">
            <img class="emoji emoji1f197" data-c="🆗">
            <img class="emoji emoji1f17f" data-c="🅿">
            <img class="emoji emoji1f198" data-c="🆘">
            <img class="emoji emoji1f199" data-c="🆙">
            <img class="emoji emoji1f19a" data-c="🆚">
            <img class="emoji emoji1f201" data-c="🈁">
            <img class="emoji emoji1f202" data-c="🈂">
            <img class="emoji emoji1f237" data-c="🈷">
            <img class="emoji emoji1f236" data-c="🈶">
            <img class="emoji emoji1f22f" data-c="🈯">
            <img class="emoji emoji1f250" data-c="🉐">
            <img class="emoji emoji1f239" data-c="🈹">
            <img class="emoji emoji1f21a" data-c="🈚">
            <img class="emoji emoji1f232" data-c="🈲">
            <img class="emoji emoji1f251" data-c="🉑">
            <img class="emoji emoji1f238" data-c="🈸">
            <img class="emoji emoji1f234" data-c="🈴">
            <img class="emoji emoji1f233" data-c="🈳">
            <img class="emoji emoji3297" data-c="㊗">
            <img class="emoji emoji3299" data-c="㊙">
            <img class="emoji emoji1f23a" data-c="🈺">
            <img class="emoji emoji1f235" data-c="🈵">
            <img class="emoji emoji25aa" data-c="▪">
            <img class="emoji emoji25ab" data-c="▫">
            <img class="emoji emoji25fb" data-c="◻">
            <img class="emoji emoji25fc" data-c="◼">
            <img class="emoji emoji25fd" data-c="◽">
            <img class="emoji emoji25fe" data-c="◾">
            <img class="emoji emoji2b1b" data-c="⬛">
            <img class="emoji emoji2b1c" data-c="⬜">
            <img class="emoji emoji1f536" data-c="🔶">
            <img class="emoji emoji1f537" data-c="🔷">
            <img class="emoji emoji1f538" data-c="🔸">
            <img class="emoji emoji1f539" data-c="🔹">
            <img class="emoji emoji1f53a" data-c="🔺">
            <img class="emoji emoji1f53b" data-c="🔻">
            <img class="emoji emoji1f4a0" data-c="💠">
            <img class="emoji emoji1f518" data-c="🔘">
            <img class="emoji emoji1f532" data-c="🔲">
            <img class="emoji emoji1f533" data-c="🔳">
            <img class="emoji emoji26aa" data-c="⚪">
            <img class="emoji emoji26ab" data-c="⚫">
            <img class="emoji emoji1f534" data-c="🔴">
            <img class="emoji emoji1f535" data-c="🔵">
        </div>
    </div>
</div>
</div>
<div class="m-l-10 m-t-10">
    <div class="btn-group dropup">
        <button type="button" class="btn btn-sm dropdown-toggle" data-toggle="dropdown">
        <img class="emoji emoji1f3c1" data-c="" data-r="1">
    </button>
    <div class="dropdown-menu dropdown-menu-left">
        <div class="dropdown-item row col-12 fbmoti">
            <img class="emoji emoji1f3c1" data-c="🏁">
            <img class="emoji emoji1f6a9" data-c="🚩">
            <img class="emoji emoji1f38c" data-c="🎌">
            <img class="emoji emoji1f3f4" data-c="🏴">
            <img class="emoji emoji1f3f3" data-c="🏳">
            <img class="emoji emoji1f3f3-200d-1f308" data-c="🏳‍🌈">
            <img class="emoji emoji1f1e6-1f1e8" data-c="🇦🇨">
            <img class="emoji emoji1f1e6-1f1e9" data-c="🇦🇩">
            <img class="emoji emoji1f1e6-1f1ea" data-c="🇦🇪">
            <img class="emoji emoji1f1e6-1f1eb" data-c="🇦🇫">
            <img class="emoji emoji1f1e6-1f1ec" data-c="🇦🇬">
            <img class="emoji emoji1f1e6-1f1ee" data-c="🇦🇮">
            <img class="emoji emoji1f1e6-1f1f1" data-c="🇦🇱">
            <img class="emoji emoji1f1e6-1f1f2" data-c="🇦🇲">
            <img class="emoji emoji1f1e6-1f1f4" data-c="🇦🇴">
            <img class="emoji emoji1f1e6-1f1f6" data-c="🇦🇶">
            <img class="emoji emoji1f1e6-1f1f7" data-c="🇦🇷">
            <img class="emoji emoji1f1e6-1f1f8" data-c="🇦🇸">
            <img class="emoji emoji1f1e6-1f1f9" data-c="🇦🇹">
            <img class="emoji emoji1f1e6-1f1fa" data-c="🇦🇺">
            <img class="emoji emoji1f1e6-1f1fc" data-c="🇦🇼">
            <img class="emoji emoji1f1e6-1f1fd" data-c="🇦🇽">
            <img class="emoji emoji1f1e6-1f1ff" data-c="🇦🇿">
            <img class="emoji emoji1f1e7-1f1e6" data-c="🇧🇦">
            <img class="emoji emoji1f1e7-1f1e7" data-c="🇧🇧">
            <img class="emoji emoji1f1e7-1f1e9" data-c="🇧🇩">
            <img class="emoji emoji1f1e7-1f1ea" data-c="🇧🇪">
            <img class="emoji emoji1f1e7-1f1eb" data-c="🇧🇫">
            <img class="emoji emoji1f1e7-1f1ec" data-c="🇧🇬">
            <img class="emoji emoji1f1e7-1f1ed" data-c="🇧🇭">
            <img class="emoji emoji1f1e7-1f1ee" data-c="🇧🇮">
            <img class="emoji emoji1f1e7-1f1ef" data-c="🇧🇯">
            <img class="emoji emoji1f1e7-1f1f1" data-c="🇧🇱">
            <img class="emoji emoji1f1e7-1f1f2" data-c="🇧🇲">
            <img class="emoji emoji1f1e7-1f1f3" data-c="🇧🇳">
            <img class="emoji emoji1f1e7-1f1f4" data-c="🇧🇴">
            <img class="emoji emoji1f1e7-1f1f6" data-c="🇧🇶">
            <img class="emoji emoji1f1e7-1f1f7" data-c="🇧🇷">
            <img class="emoji emoji1f1e7-1f1f8" data-c="🇧🇸">
            <img class="emoji emoji1f1e7-1f1f9" data-c="🇧🇹">
            <img class="emoji emoji1f1e7-1f1fb" data-c="🇧🇻">
            <img class="emoji emoji1f1e7-1f1fc" data-c="🇧🇼">
            <img class="emoji emoji1f1e7-1f1fe" data-c="🇧🇾">
            <img class="emoji emoji1f1e7-1f1ff" data-c="🇧🇿">
            <img class="emoji emoji1f1e8-1f1e6" data-c="🇨🇦">
            <img class="emoji emoji1f1e8-1f1e8" data-c="🇨🇨">
            <img class="emoji emoji1f1e8-1f1e9" data-c="🇨🇩">
            <img class="emoji emoji1f1e8-1f1eb" data-c="🇨🇫">
            <img class="emoji emoji1f1e8-1f1ec" data-c="🇨🇬">
            <img class="emoji emoji1f1e8-1f1ed" data-c="🇨🇭">
            <img class="emoji emoji1f1e8-1f1ee" data-c="🇨🇮">
            <img class="emoji emoji1f1e8-1f1f0" data-c="🇨🇰">
            <img class="emoji emoji1f1e8-1f1f1" data-c="🇨🇱">
            <img class="emoji emoji1f1e8-1f1f2" data-c="🇨🇲">
            <img class="emoji emoji1f1e8-1f1f3" data-c="🇨🇳">
            <img class="emoji emoji1f1e8-1f1f4" data-c="🇨🇴">
            <img class="emoji emoji1f1e8-1f1f5" data-c="🇨🇵">
            <img class="emoji emoji1f1e8-1f1f7" data-c="🇨🇷">
            <img class="emoji emoji1f1e8-1f1fa" data-c="🇨🇺">
            <img class="emoji emoji1f1e8-1f1fb" data-c="🇨🇻">
            <img class="emoji emoji1f1e8-1f1fc" data-c="🇨🇼">
            <img class="emoji emoji1f1e8-1f1fd" data-c="🇨🇽">
            <img class="emoji emoji1f1e8-1f1fe" data-c="🇨🇾">
            <img class="emoji emoji1f1e8-1f1ff" data-c="🇨🇿">
            <img class="emoji emoji1f1e9-1f1ea" data-c="🇩🇪">
            <img class="emoji emoji1f1e9-1f1ec" data-c="🇩🇬">
            <img class="emoji emoji1f1e9-1f1ef" data-c="🇩🇯">
            <img class="emoji emoji1f1e9-1f1f0" data-c="🇩🇰">
            <img class="emoji emoji1f1e9-1f1f2" data-c="🇩🇲">
            <img class="emoji emoji1f1e9-1f1f4" data-c="🇩🇴">
            <img class="emoji emoji1f1e9-1f1ff" data-c="🇩🇿">
            <img class="emoji emoji1f1ea-1f1e6" data-c="🇪🇦">
            <img class="emoji emoji1f1ea-1f1e8" data-c="🇪🇨">
            <img class="emoji emoji1f1ea-1f1ea" data-c="🇪🇪">
            <img class="emoji emoji1f1ea-1f1ec" data-c="🇪🇬">
            <img class="emoji emoji1f1ea-1f1ed" data-c="🇪🇭">
            <img class="emoji emoji1f1ea-1f1f7" data-c="🇪🇷">
            <img class="emoji emoji1f1ea-1f1f8" data-c="🇪🇸">
            <img class="emoji emoji1f1ea-1f1f9" data-c="🇪🇹">
            <img class="emoji emoji1f1ea-1f1fa" data-c="🇪🇺">
            <img class="emoji emoji1f1eb-1f1ee" data-c="🇫🇮">
            <img class="emoji emoji1f1eb-1f1ef" data-c="🇫🇯">
            <img class="emoji emoji1f1eb-1f1f0" data-c="🇫🇰">
            <img class="emoji emoji1f1eb-1f1f2" data-c="🇫🇲">
            <img class="emoji emoji1f1eb-1f1f4" data-c="🇫🇴">
            <img class="emoji emoji1f1eb-1f1f7" data-c="🇫🇷">
            <img class="emoji emoji1f1ec-1f1e6" data-c="🇬🇦">
            <img class="emoji emoji1f1ec-1f1e7" data-c="🇬🇧">
            <img class="emoji emoji1f1ec-1f1e9" data-c="🇬🇩">
            <img class="emoji emoji1f1ec-1f1ea" data-c="🇬🇪">
            <img class="emoji emoji1f1ec-1f1eb" data-c="🇬🇫">
            <img class="emoji emoji1f1ec-1f1ec" data-c="🇬🇬">
            <img class="emoji emoji1f1ec-1f1ed" data-c="🇬🇭">
            <img class="emoji emoji1f1ec-1f1ee" data-c="🇬🇮">
            <img class="emoji emoji1f1ec-1f1f1" data-c="🇬🇱">
            <img class="emoji emoji1f1ec-1f1f2" data-c="🇬🇲">
            <img class="emoji emoji1f1ec-1f1f3" data-c="🇬🇳">
            <img class="emoji emoji1f1ec-1f1f5" data-c="🇬🇵">
            <img class="emoji emoji1f1ec-1f1f6" data-c="🇬🇶">
            <img class="emoji emoji1f1ec-1f1f7" data-c="🇬🇷">
            <img class="emoji emoji1f1ec-1f1f8" data-c="🇬🇸">
            <img class="emoji emoji1f1ec-1f1f9" data-c="🇬🇹">
            <img class="emoji emoji1f1ec-1f1fa" data-c="🇬🇺">
            <img class="emoji emoji1f1ec-1f1fc" data-c="🇬🇼">
            <img class="emoji emoji1f1ec-1f1fe" data-c="🇬🇾">
            <img class="emoji emoji1f1ed-1f1f0" data-c="🇭🇰">
            <img class="emoji emoji1f1ed-1f1f2" data-c="🇭🇲">
            <img class="emoji emoji1f1ed-1f1f3" data-c="🇭🇳">
            <img class="emoji emoji1f1ed-1f1f7" data-c="🇭🇷">
            <img class="emoji emoji1f1ed-1f1f9" data-c="🇭🇹">
            <img class="emoji emoji1f1ed-1f1fa" data-c="🇭🇺">
            <img class="emoji emoji1f1ee-1f1e8" data-c="🇮🇨">
            <img class="emoji emoji1f1ee-1f1e9" data-c="🇮🇩">
            <img class="emoji emoji1f1ee-1f1ea" data-c="🇮🇪">
            <img class="emoji emoji1f1ee-1f1f1" data-c="🇮🇱">
            <img class="emoji emoji1f1ee-1f1f2" data-c="🇮🇲">
            <img class="emoji emoji1f1ee-1f1f3" data-c="🇮🇳">
            <img class="emoji emoji1f1ee-1f1f4" data-c="🇮🇴">
            <img class="emoji emoji1f1ee-1f1f6" data-c="🇮🇶">
            <img class="emoji emoji1f1ee-1f1f7" data-c="🇮🇷">
            <img class="emoji emoji1f1ee-1f1f8" data-c="🇮🇸">
            <img class="emoji emoji1f1ee-1f1f9" data-c="🇮🇹">
            <img class="emoji emoji1f1ef-1f1ea" data-c="🇯🇪">
            <img class="emoji emoji1f1ef-1f1f2" data-c="🇯🇲">
            <img class="emoji emoji1f1ef-1f1f4" data-c="🇯🇴">
            <img class="emoji emoji1f1ef-1f1f5" data-c="🇯🇵">
            <img class="emoji emoji1f1f0-1f1ea" data-c="🇰🇪">
            <img class="emoji emoji1f1f0-1f1ec" data-c="🇰🇬">
            <img class="emoji emoji1f1f0-1f1ed" data-c="🇰🇭">
            <img class="emoji emoji1f1f0-1f1ee" data-c="🇰🇮">
            <img class="emoji emoji1f1f0-1f1f2" data-c="🇰🇲">
            <img class="emoji emoji1f1f0-1f1f3" data-c="🇰🇳">
            <img class="emoji emoji1f1f0-1f1f5" data-c="🇰🇵">
            <img class="emoji emoji1f1f0-1f1f7" data-c="🇰🇷">
            <img class="emoji emoji1f1f0-1f1fc" data-c="🇰🇼">
            <img class="emoji emoji1f1f0-1f1fe" data-c="🇰🇾">
            <img class="emoji emoji1f1f0-1f1ff" data-c="🇰🇿">
            <img class="emoji emoji1f1f1-1f1e6" data-c="🇱🇦">
            <img class="emoji emoji1f1f1-1f1e7" data-c="🇱🇧">
            <img class="emoji emoji1f1f1-1f1e8" data-c="🇱🇨">
            <img class="emoji emoji1f1f1-1f1ee" data-c="🇱🇮">
            <img class="emoji emoji1f1f1-1f1f0" data-c="🇱🇰">
            <img class="emoji emoji1f1f1-1f1f7" data-c="🇱🇷">
            <img class="emoji emoji1f1f1-1f1f8" data-c="🇱🇸">
            <img class="emoji emoji1f1f1-1f1f9" data-c="🇱🇹">
            <img class="emoji emoji1f1f1-1f1fa" data-c="🇱🇺">
            <img class="emoji emoji1f1f1-1f1fb" data-c="🇱🇻">
            <img class="emoji emoji1f1f1-1f1fe" data-c="🇱🇾">
            <img class="emoji emoji1f1f2-1f1e6" data-c="🇲🇦">
            <img class="emoji emoji1f1f2-1f1e8" data-c="🇲🇨">
            <img class="emoji emoji1f1f2-1f1e9" data-c="🇲🇩">
            <img class="emoji emoji1f1f2-1f1ea" data-c="🇲🇪">
            <img class="emoji emoji1f1f2-1f1eb" data-c="🇲🇫">
            <img class="emoji emoji1f1f2-1f1ec" data-c="🇲🇬">
            <img class="emoji emoji1f1f2-1f1ed" data-c="🇲🇭">
            <img class="emoji emoji1f1f2-1f1f0" data-c="🇲🇰">
            <img class="emoji emoji1f1f2-1f1f1" data-c="🇲🇱">
            <img class="emoji emoji1f1f2-1f1f2" data-c="🇲🇲">
            <img class="emoji emoji1f1f2-1f1f3" data-c="🇲🇳">
            <img class="emoji emoji1f1f2-1f1f4" data-c="🇲🇴">
            <img class="emoji emoji1f1f2-1f1f5" data-c="🇲🇵">
            <img class="emoji emoji1f1f2-1f1f6" data-c="🇲🇶">
            <img class="emoji emoji1f1f2-1f1f7" data-c="🇲🇷">
            <img class="emoji emoji1f1f2-1f1f8" data-c="🇲🇸">
            <img class="emoji emoji1f1f2-1f1f9" data-c="🇲🇹">
            <img class="emoji emoji1f1f2-1f1fa" data-c="🇲🇺">
            <img class="emoji emoji1f1f2-1f1fb" data-c="🇲🇻">
            <img class="emoji emoji1f1f2-1f1fc" data-c="🇲🇼">
            <img class="emoji emoji1f1f2-1f1fd" data-c="🇲🇽">
            <img class="emoji emoji1f1f2-1f1fe" data-c="🇲🇾">
            <img class="emoji emoji1f1f2-1f1ff" data-c="🇲🇿">
            <img class="emoji emoji1f1f3-1f1e6" data-c="🇳🇦">
            <img class="emoji emoji1f1f3-1f1e8" data-c="🇳🇨">
            <img class="emoji emoji1f1f3-1f1ea" data-c="🇳🇪">
            <img class="emoji emoji1f1f3-1f1eb" data-c="🇳🇫">
            <img class="emoji emoji1f1f3-1f1ec" data-c="🇳🇬">
            <img class="emoji emoji1f1f3-1f1ee" data-c="🇳🇮">
            <img class="emoji emoji1f1f3-1f1f1" data-c="🇳🇱">
            <img class="emoji emoji1f1f3-1f1f4" data-c="🇳🇴">
            <img class="emoji emoji1f1f3-1f1f5" data-c="🇳🇵">
            <img class="emoji emoji1f1f3-1f1f7" data-c="🇳🇷">
            <img class="emoji emoji1f1f3-1f1fa" data-c="🇳🇺">
            <img class="emoji emoji1f1f3-1f1ff" data-c="🇳🇿">
            <img class="emoji emoji1f1f4-1f1f2" data-c="🇴🇲">
            <img class="emoji emoji1f1f5-1f1e6" data-c="🇵🇦">
            <img class="emoji emoji1f1f5-1f1ea" data-c="🇵🇪">
            <img class="emoji emoji1f1f5-1f1eb" data-c="🇵🇫">
            <img class="emoji emoji1f1f5-1f1ec" data-c="🇵🇬">
            <img class="emoji emoji1f1f5-1f1ed" data-c="🇵🇭">
            <img class="emoji emoji1f1f5-1f1f0" data-c="🇵🇰">
            <img class="emoji emoji1f1f5-1f1f1" data-c="🇵🇱">
            <img class="emoji emoji1f1f5-1f1f2" data-c="🇵🇲">
            <img class="emoji emoji1f1f5-1f1f3" data-c="🇵🇳">
            <img class="emoji emoji1f1f5-1f1f7" data-c="🇵🇷">
            <img class="emoji emoji1f1f5-1f1f8" data-c="🇵🇸">
            <img class="emoji emoji1f1f5-1f1f9" data-c="🇵🇹">
            <img class="emoji emoji1f1f5-1f1fc" data-c="🇵🇼">
            <img class="emoji emoji1f1f5-1f1fe" data-c="🇵🇾">
            <img class="emoji emoji1f1f6-1f1e6" data-c="🇶🇦">
            <img class="emoji emoji1f1f7-1f1ea" data-c="🇷🇪">
            <img class="emoji emoji1f1f7-1f1f4" data-c="🇷🇴">
            <img class="emoji emoji1f1f7-1f1f8" data-c="🇷🇸">
            <img class="emoji emoji1f1f7-1f1fa" data-c="🇷🇺">
            <img class="emoji emoji1f1f7-1f1fc" data-c="🇷🇼">
            <img class="emoji emoji1f1f8-1f1e6" data-c="🇸🇦">
            <img class="emoji emoji1f1f8-1f1e7" data-c="🇸🇧">
            <img class="emoji emoji1f1f8-1f1e8" data-c="🇸🇨">
            <img class="emoji emoji1f1f8-1f1e9" data-c="🇸🇩">
            <img class="emoji emoji1f1f8-1f1ea" data-c="🇸🇪">
            <img class="emoji emoji1f1f8-1f1ec" data-c="🇸🇬">
            <img class="emoji emoji1f1f8-1f1ed" data-c="🇸🇭">
            <img class="emoji emoji1f1f8-1f1ee" data-c="🇸🇮">
            <img class="emoji emoji1f1f8-1f1ef" data-c="🇸🇯">
            <img class="emoji emoji1f1f8-1f1f0" data-c="🇸🇰">
            <img class="emoji emoji1f1f8-1f1f1" data-c="🇸🇱">
            <img class="emoji emoji1f1f8-1f1f2" data-c="🇸🇲">
            <img class="emoji emoji1f1f8-1f1f3" data-c="🇸🇳">
            <img class="emoji emoji1f1f8-1f1f4" data-c="🇸🇴">
            <img class="emoji emoji1f1f8-1f1f7" data-c="🇸🇷">
            <img class="emoji emoji1f1f8-1f1f8" data-c="🇸🇸">
            <img class="emoji emoji1f1f8-1f1f9" data-c="🇸🇹">
            <img class="emoji emoji1f1f8-1f1fb" data-c="🇸🇻">
            <img class="emoji emoji1f1f8-1f1fd" data-c="🇸🇽">
            <img class="emoji emoji1f1f8-1f1fe" data-c="🇸🇾">
            <img class="emoji emoji1f1f8-1f1ff" data-c="🇸🇿">
            <img class="emoji emoji1f1f9-1f1e6" data-c="🇹🇦">
            <img class="emoji emoji1f1f9-1f1e8" data-c="🇹🇨">
            <img class="emoji emoji1f1f9-1f1e9" data-c="🇹🇩">
            <img class="emoji emoji1f1f9-1f1eb" data-c="🇹🇫">
            <img class="emoji emoji1f1f9-1f1ec" data-c="🇹🇬">
            <img class="emoji emoji1f1f9-1f1ed" data-c="🇹🇭">
            <img class="emoji emoji1f1f9-1f1ef" data-c="🇹🇯">
            <img class="emoji emoji1f1f9-1f1f0" data-c="🇹🇰">
            <img class="emoji emoji1f1f9-1f1f1" data-c="🇹🇱">
            <img class="emoji emoji1f1f9-1f1f2" data-c="🇹🇲">
            <img class="emoji emoji1f1f9-1f1f3" data-c="🇹🇳">
            <img class="emoji emoji1f1f9-1f1f4" data-c="🇹🇴">
            <img class="emoji emoji1f1f9-1f1f7" data-c="🇹🇷">
            <img class="emoji emoji1f1f9-1f1f9" data-c="🇹🇹">
            <img class="emoji emoji1f1f9-1f1fb" data-c="🇹🇻">
            <img class="emoji emoji1f1f9-1f1fc" data-c="🇹🇼">
            <img class="emoji emoji1f1f9-1f1ff" data-c="🇹🇿">
            <img class="emoji emoji1f1fa-1f1e6" data-c="🇺🇦">
            <img class="emoji emoji1f1fa-1f1ec" data-c="🇺🇬">
            <img class="emoji emoji1f1fa-1f1f2" data-c="🇺🇲">
            <img class="emoji emoji1f1fa-1f1f3" data-c="🇺🇳">
            <img class="emoji emoji1f1fa-1f1f8" data-c="🇺🇸">
            <img class="emoji emoji1f1fa-1f1fe" data-c="🇺🇾">
            <img class="emoji emoji1f1fa-1f1ff" data-c="🇺🇿">
            <img class="emoji emoji1f1fb-1f1e6" data-c="🇻🇦">
            <img class="emoji emoji1f1fb-1f1e8" data-c="🇻🇨">
            <img class="emoji emoji1f1fb-1f1ea" data-c="🇻🇪">
            <img class="emoji emoji1f1fb-1f1ec" data-c="🇻🇬">
            <img class="emoji emoji1f1fb-1f1ee" data-c="🇻🇮">
            <img class="emoji emoji1f1fb-1f1f3" data-c="🇻🇳">
            <img class="emoji emoji1f1fb-1f1fa" data-c="🇻🇺">
            <img class="emoji emoji1f1fc-1f1eb" data-c="🇼🇫">
            <img class="emoji emoji1f1fc-1f1f8" data-c="🇼🇸">
            <img class="emoji emoji1f1fd-1f1f0" data-c="🇽🇰">
            <img class="emoji emoji1f1fe-1f1ea" data-c="🇾🇪">
            <img class="emoji emoji1f1fe-1f1f9" data-c="🇾🇹">
            <img class="emoji emoji1f1ff-1f1e6" data-c="🇿🇦">
            <img class="emoji emoji1f1ff-1f1f2" data-c="🇿🇲">
            <img class="emoji emoji1f1ff-1f1fc" data-c="🇿🇼">
            <img class="emoji emoji1f3f4-e0067-e0062-e0065-e006e-e0067-e007f" data-c="🏴󠁧󠁢󠁥󠁮󠁧󠁿">
            <img class="emoji emoji1f3f4-e0067-e0062-e0073-e0063-e0074-e007f" data-c="🏴󠁧󠁢󠁳󠁣󠁴󠁿">
            <img class="emoji emoji1f3f4-e0067-e0062-e0077-e006c-e0073-e007f" data-c="🏴󠁧󠁢󠁷󠁬󠁳󠁿">
        </div>
    </div>
</div>
</div>
<script>
    function h(el) {
        var ef = $(el).closest('form').find('.sms');
        var va = $(ef).val() + " " + $(el).attr('data-c') + " ";
        var s = $(el).attr('data-r');
        if (s === undefined) {
            $(ef).val(va);
        }
    }

    $('.emoji').on('click', function (e) {
        h(this);

    });
    {{--
var f = $('[data-cat="flags"]').find('.emoji');
$.each(f, function (k, v) {
    $(v).click();
});
--}}


</script>